### ISSUE TITLE
New driver version 1.1.62 was released

### ISSUE THREAD

**Issue by tssk** [AdnanHodzic/displaylink-debian#10]
Displaylink released new version od driver for Ubuntu

http://www.displaylink.com/downloads/file?id=607

The installer script still does not work with Debian.

**Comment by AdnanHodzic** [comment]
Fixed in [latest commit](https://github.com/AdnanHodzic/displaylink-debian/commit/7eb3e401792301400dc9ba17cc6db0697ed88fe5).

Please pull the latest version of displaylink-debian and run it.
