### ISSUE TITLE
Can't install on Debian

### ISSUE THREAD

**Issue by mapomme1108** [AdnanHodzic/displaylink-debian#102]
Hello,

I want to install the DisplayLink driver on Debian but when I run the shell script, I have this error message 

`./displaylink-debian.sh: line 7: syntax error near the unexpected symbol « newline »
./displaylink-debian.sh: line 7: `<!DOCTYPE html>'`

What is the problem?

Thanks!

**Comment by medbs** [comment]
What version of Debian are you using ?

**Comment by mapomme1108** [comment]
Hello,

Debian 9.2.1

**Comment by AdnanHodzic** [comment]
@mapomme1108 problem is with your setup, see these issues for reference:

https://github.com/AdnanHodzic/displaylink-debian/issues/89
https://github.com/AdnanHodzic/displaylink-debian/issues/65
