### ISSUE TITLE
elementary OS Loki Support

### ISSUE THREAD

**Issue by cassidyjames** [AdnanHodzic/displaylink-debian#11]
elementary OS Loki is coming out soon and is based on an Ubuntu 16.04 LTS core. I have tested the driver after spoofing Ubuntu 16.04 in the lsb_release and it worked well.

**Comment by AdnanHodzic** [comment]
In my latest commit I've added support for Elementary Loki. 

Enjoy, and let me know if you have any additional questions and/or comments.
