### ISSUE TITLE
(dkms install evdi/4.2.29 && modprobe evdi) (code=exited, status=1/FAILURE)

### ISSUE THREAD

**Issue by m1gwel** [AdnanHodzic/displaylink-debian#123]
Everything seemed to install ok on Debian 9 but when I run  systemctl status dlm.service it gives the following error;

● dlm.service - DisplayLink Manager Service
   Loaded: loaded (/lib/systemd/system/dlm.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-03-28 18:17:45 BST; 1s ago
  Process: 4432 ExecStartPre=/bin/sh -c modprobe evdi || (dkms install evdi/4.2.29 && modprobe evdi) (code=exited, status=1/FAILURE)

**Comment by rotten** [comment]
Why?

**Comment by caniko2** [comment]
I can't disable UEFI on my notebook. Please help
