### ISSUE TITLE
Weird graphics issue

### ISSUE THREAD

**Issue by unalterable** [AdnanHodzic/displaylink-debian#126]
Since using your excellent script to add displaylink functionality to my HP running ubuntu 17.10, i get this annoying graphics issue: https://i.stack.imgur.com/MJ7KS.jpg. It flickers on and off, and the corruption tends to move as a move the mouse.

I'm one of those who also have to add the file /etc/X11/xorg.conf with the following content:

```
Section "Device"
    Identifier "Intel"
    Driver "intel"
EndSection
```

I have tried many many alternative settings in this file to get rid of the issue but i don't really know what i'm doing.

Can anyone help?

**Comment by AdnanHodzic** [comment]
In latest commit, I've added code which will now allow "displaylink-debian" to automatically configure your Xorg config based on your graphics card. 

This feature may still be bit rough around the edges and might need some improvement. So if you have still have problems after pulling latest changes and running "re-install", please re-open this story and add output of following commands:

`cat /etc/X11/xorg.conf.d/20-displaylink.conf`
`lspci | grep -i vga`
`lspci -nnk | grep -i vga -A3 | grep 'in use'|cut -d":" -f2|sed 's/ //g'`
`lspci -nnk | grep -i vga -A3|grep Subsystem|cut -d" " -f5`
