### ISSUE TITLE
Syntax error: "(" unexpected (expecting "fi")

### ISSUE THREAD

**Issue by pmgate** [AdnanHodzic/displaylink-debian#133]
Downloaded displaylink-debian-master.zip then running the script with sh ./displaylink-debian.sh produces the following error: 

displaylink-debian.sh: 38: displaylink-debian.sh: Syntax error: "(" unexpected (expecting "fi")

==============
HP Probook 450 G3 with Mint 18.2 Sonya

**Comment by ISMAELMARTINEZ** [comment]
just run ./displaylink-debian.sh (without the sh)

**Comment by Cyb0org** [comment]
Do not use "sh" only "bash" (look at the first line in script). You have /bin/sh linked to /bin/dash.

**Comment by AdnanHodzic** [comment]
Issue reported in [Troubleshoot most common problems](https://github.com/AdnanHodzic/displaylink-debian/blob/master/post-install-guide.md#troubleshooting-most-common-issues)
