### ISSUE TITLE
Blurred font

### ISSUE THREAD

**Issue by Sykomaniac** [AdnanHodzic/displaylink-debian#143]
Not sure this is an issue with the driver but after installing everything on Ubuntu 18.04 any app displayed on the external monitor has a blurred font - any idea how to resolve this?

**Comment by AdnanHodzic** [comment]
You could reporting this [problem to upstream](https://github.com/DisplayLink/evdi/issues). 

I'm also closing the issue, please feel free to re-open it if you're still facing the same issue. As it could be due to different factors, i.e: X server version
