### ISSUE TITLE
Only Displaylink Monitor?

### ISSUE THREAD

**Issue by gagarwa** [AdnanHodzic/displaylink-debian#147]
This issue is only to help others save time.  (Maybe add to readme?)

I wanted to only attach my displaylink monitor since I don't have a real one available (and am on desktop).  However, as it turns out, you can't make a computer recognize a displaylink monitor as a monitor.  It works only by extending a real monitor.  Things look strangely on vnc too.  

The best solution is to use a monitor emulator device (cheapest option) or a converter cable (not sure if it will work, and more expensive).  I tried looking for software options, like vnc, but they don't deliver.  Xandr completely fails, as there is no physical monitor.  If anyone knows better options, please list below.

**Comment by jribal** [comment]
Hi, It is possible to setup an external display link monitor only.
I use a mini itx n3700 motherboard, an ASUS MB169B+ 15.6" and ubuntu 18.04 and gnome shell.
I would suggest to use ubuntu, you might have less issues. I moved from debian testing to ubuntu only to use the external displaylink monitor.

I used a plugged monitor to do the system install and basic setup. Basic setup can be done using command line if you find the good ones.

Use displaylink-debian then you have to disable wayland in gdm and in the session you want to use.
[disable wayland on gdm](https://askubuntu.com/questions/975094/how-to-disable-wayland-in-17-10-in-gdm3-login-screen)
Then it works as a regular display with + more cpu usage. I can plug/unplug or go to suspend as usual.

**Comment by AdnanHodzic** [comment]
@gagarwa please feel free to add anything you think is missing to the [post installation guide](https://github.com/AdnanHodzic/displaylink-debian/blob/master/post-install-guide.md). I would like if all necessary information could be there.

**Comment by AdnanHodzic** [comment]
In latest commit, I've added code which will now allow "displaylink-debian" to automatically configure your Xorg config based on your graphics card. 

This feature may still be bit rough around the edges and might need some improvement. So if you have still have problems after pulling latest changes and running "re-install", please re-open this story and add output of following commands:

`cat /etc/X11/xorg.conf.d/20-displaylink.conf`
`lspci | grep -i vga`
`lspci -nnk | grep -i vga -A3 | grep 'in use'|cut -d":" -f2|sed 's/ //g'`
`lspci -nnk | grep -i vga -A3|grep Subsystem|cut -d" " -f5`
