### ISSUE TITLE
Nvidia GPU - Pointer Lagg and Not Trusted Key

### ISSUE THREAD

**Issue by MrEdinLaw** [AdnanHodzic/displaylink-debian#149]
After installing the first thing i saw was lagg under the pointer:
 - If i didn't move the pointer a literal cube under it wouldn't update.

After a restart i had another problem multiple keys would report not signed and the system wouldn't boot.

Tested on:
Ubuntu 18.04
GeForce MX150

Pozdrav

**Comment by AdnanHodzic** [comment]
In latest commit, I've added code which will now allow "displaylink-debian" to automatically configure your Xorg config based on your graphics card. 

This feature may still be bit rough around the edges and might need some improvement. So if you have still have problems after pulling latest changes and running "re-install", please re-open this story and add output of following commands:

`cat /etc/X11/xorg.conf.d/20-displaylink.conf`
`lspci | grep -i vga`
`lspci -nnk | grep -i vga -A3 | grep 'in use'|cut -d":" -f2|sed 's/ //g'`
`lspci -nnk | grep -i vga -A3|grep Subsystem|cut -d" " -f5`
