### ISSUE TITLE
I do xrandr --setprovideroutputsource 2 0 it gives me an error

### ISSUE THREAD

**Issue by DayehT5N** [AdnanHodzic/displaylink-debian#150]
It gives me this error: X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  35 (RRSetProviderOutputSource)
  Value in failed request:  0x3f
  Serial number of failed request:  17
  Current serial number in output stream:  18

i have 2 moniters one of them i want to use it using a USB adapter but the moniter connected to the USB one not working plz help

**Comment by bobs-bits** [comment]
Hi DayehtT5N, 

how did you fix this?  I have the same error message :)
