### ISSUE TITLE
Not working in mint 19

### ISSUE THREAD

**Issue by neeraj9194** [AdnanHodzic/displaylink-debian#154]
It installed fine but did nothing(display not detected) in mint 19....any idea why??

**Comment by neeraj9194** [comment]
sorry it worked I had to disable secure boot and reinstall it...
https://support.displaylink.com/knowledgebase/articles/1181617-how-to-use-displaylink-ubuntu-driver-with-uefi-sec

**Comment by AdnanHodzic** [comment]
Glad you were able to figure it out, this step is mentioned as part of the [Post Installation Guide](https://github.com/AdnanHodzic/displaylink-debian/blob/master/post-install-guide.md) but unfortunately not a lot of people look at it after install.
