### ISSUE TITLE
Screen flipping

### ISSUE THREAD

**Issue by vladrulez** [AdnanHodzic/displaylink-debian#155]
Hello,
You script is working fine on Ubuntu 18.04 with Unity, but I have a problem with screen flipping.
Parts of screens flips from time to time and it is really annoying. Sometimes you web browser could show previous pages instead off the current one, etc.
Do you have any ideas how it could be fixed? I am using Intel onboard video on HM370 chipset.

**Comment by AdnanHodzic** [comment]
In latest commit, I've added code which will now allow "displaylink-debian" to automatically configure your Xorg config based on your graphics card. 

This feature may still be bit rough around the edges and might need some improvement. So if you have still have problems after pulling latest changes and running "re-install", please re-open this story and add output of following commands:

`cat /etc/X11/xorg.conf.d/20-displaylink.conf`
`lspci | grep -i vga`
`lspci -nnk | grep -i vga -A3 | grep 'in use'|cut -d":" -f2|sed 's/ //g'`
`lspci -nnk | grep -i vga -A3|grep Subsystem|cut -d" " -f5`
