### ISSUE TITLE
display link driver install uses an invalid key

### ISSUE THREAD

**Issue by rstaylor** [AdnanHodzic/displaylink-debian#158]
-- 
-- Unit dlm.service has failed.
-- 
-- The result is RESULT.
lines 2139-2161/2161 (END)
-- Support: http://www.ubuntu.com/support
-- 
-- Unit dlm.service has finished shutting down.
Sep 15 15:18:09 ritaylor-Precision-5510 systemd[1]: Starting DisplayLink Manager Service...
-- Subject: Unit dlm.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit dlm.service has begun starting up.
Sep 15 15:18:09 ritaylor-Precision-5510 sh[9970]: modprobe: ERROR: could not insert 'evdi': Required key not available
Sep 15 15:18:10 ritaylor-Precision-5510 sh[9970]: Module evdi/4.2.29 already installed on kernel 4.15.0-34-generic/x86_64
Sep 15 15:18:10 ritaylor-Precision-5510 sh[9970]: modprobe: ERROR: could not insert 'evdi': Required key not available
Sep 15 15:18:10 ritaylor-Precision-5510 systemd[1]: dlm.service: Control process exited, code=exited status=1
Sep 15 15:18:10 ritaylor-Precision-5510 systemd[1]: dlm.service: Failed with result 'exit-code'.
**Sep 15 15:18:10 ritaylor-Precision-5510 kernel: PKCS#7 signature not signed with a trusted key
Sep 15 15:18:10 ritaylor-Precision-5510 systemd[1]: Failed to start DisplayLink Manager Service.
-- Subject: Unit dlm.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support**
-- 
-- Unit dlm.service has failed.
-- 
-- The result is RESULT.
lines 2139-2161/2161 (END)
-- Support: http://www.ubuntu.com/support
-- 
-- Unit dlm.service has finished shutting down.
Sep 15 15:18:09 ritaylor-Precision-5510 systemd[1]: Starting DisplayLink Manager Service...
-- Subject: Unit dlm.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit dlm.service has begun starting up.
Sep 15 15:18:09 ritaylor-Precision-5510 sh[9970]: modprobe: ERROR: could not insert 'evdi': Required key not available
Sep 15 15:18:10 ritaylor-Precision-5510 sh[9970]: Module evdi/4.2.29 already installed on kernel 4.15.0-34-generic/x86_64
Sep 15 15:18:10 ritaylor-Precision-5510 sh[9970]: modprobe: ERROR: could not insert 'evdi': Required key not available
Sep 15 15:18:10 ritaylor-Precision-5510 systemd[1]: dlm.service: Control process exited, code=exited status=1

**Sep 15 15:18:10 ritaylor-Precision-5510 systemd[1]: dlm.service: Failed with result 'exit-code'.
Sep 15 15:18:10 ritaylor-Precision-5510 kernel: PKCS#7 signature not signed with a trusted key
Sep 15 15:18:10 ritaylor-Precision-5510 systemd[1]: Failed to start DisplayLink Manager Service.
-- Subject: Unit dlm.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--** 

-- Unit dlm.service has failed.
-- 
-- The result is RESULT.

**Comment by rstaylor** [comment]
Sep 15 15:26:03 ritaylor-Precision-5510 kernel: PKCS#7 signature not signed with a trusted key
Sep 15 15:26:08 ritaylor-Precision-5510 systemd[1]: dlm.service: Service hold-off time over, scheduling restart.
Sep 15 15:26:08 ritaylor-Precision-5510 systemd[1]: dlm.service: Scheduled restart job, restart counter is at 150.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support

**Comment by AdnanHodzic** [comment]
Have you disabled UEFI (secure boot) as suggested on https://github.com/AdnanHodzic/displaylink-debian/blob/master/post-install-guide.md#most-common-ubuntu-related-issues
