### ISSUE TITLE
X crash after setting the screen

### ISSUE THREAD

**Issue by hadogenes** [AdnanHodzic/displaylink-debian#161]
Hi,
I have a problem that X always crash after setting displays with _xrandr_
I have 2 monitors so I run
> xrandr --setprovideroutputsource 1 0
> xrandr --setprovideroutputsource 2 0

and than
> xrandr --output DVI-I-2-1 --auto --same-as eDP-1
> (crash)
> xrandr --output DVI-I-3-1 --auto --right-of DVI-I-2-1

always crashes, but after X restarts I can set the displays correctly without a problem with the same commands

My logs:
[Xorg.0.log](https://github.com/AdnanHodzic/displaylink-debian/files/2457384/Xorg.0.log)
[dmesg.log](https://github.com/AdnanHodzic/displaylink-debian/files/2457389/dmesg.log)

**Comment by AdnanHodzic** [comment]
Closing this issue as it's related to issue where your graphics card is not properly supported, let's continue the discussion here: https://github.com/AdnanHodzic/displaylink-debian/issues/162
