### ISSUE TITLE
Doesn't work on Kali 2018.4 

### ISSUE THREAD

**Issue by jokeralood** [AdnanHodzic/displaylink-debian#177]
help me pliz is not work in my kali linux 2018.4

**Comment by AdnanHodzic** [comment]
@jokeralood what doesn't work, can you provide the output of what happens when you run "install"

**Comment by jokeralood** [comment]
the instal install complet but after i reboot but the scren in display not work

**Comment by AdnanHodzic** [comment]
what is the output of these 3 commands:

`lspci | grep -i vga`
`lspci -nnk | grep -i vga -A3 | grep 'in use'|cut -d":" -f2|sed 's/ //g'`
`cat /etc/X11/xorg.conf.d/20-displaylink.conf`

**Comment by jokeralood** [comment]
# lspci | grep -i vga
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 520 (rev 07)
# lspci -nnk | grep -i vga -A3 | grep 'in use'|cut -d":" -f2|sed 's/ //g'
i915
# cat /etc/X11/xorg.conf.d/20-displaylink.conf
Section "Device"
  Identifier  "Intel"
  Driver      "intel"
EndSection

**Comment by jokeralood** [comment]
# echo $XDG_SESSION_TYPE
x11
:~# dmesg | grep Display
[    3.458304] usb 2-4.1: Manufacturer: DisplayLink

**Comment by jokeralood** [comment]
help me plizz

**Comment by AdnanHodzic** [comment]
@jokeralood ok please add following as your `/etc/X11/xorg.conf.d/20-displaylink.conf` contents:

```
Section "Device"
  Identifier  "Intel"
  Driver      "intel"
EndSection
```

and logout and re-login to X11 session and everything should be working as expected.

**Comment by AdnanHodzic** [comment]
In latest commit, I've added code which will now allow "displaylink-debian" to automatically configure your Xorg config based on your graphics card. 

This feature may still be bit rough around the edges and might need some improvement. So if you have still have problems after pulling latest changes and running "re-install", please re-open this story and add output of following commands:

`cat /etc/X11/xorg.conf.d/20-displaylink.conf`
`lspci | grep -i vga`
`lspci -nnk | grep -i vga -A3 | grep 'in use'|cut -d":" -f2|sed 's/ //g'`
`lspci -nnk | grep -i vga -A3|grep Subsystem|cut -d" " -f5`
