### ISSUE TITLE
 Displaylink with AMD Ryzen 5 2500U GPU

### ISSUE THREAD

**Issue by Tegaf** [AdnanHodzic/displaylink-debian#180]
Hi,
AMD Ryzen 5 2500U, Ubuntu 18.10 (kernel 4.18)
The script works, but everything is slow and the process of displaylink takes 100% of the cpu. Any idea?
Thanks!

**Comment by Tegaf** [comment]
Hmmmm I have set `/etc/X11/xorg.conf.d/20-displaylink.conf` as 

```
Section "Device"
    Identifier "AMDGPU"
    Driver "amdgpu"
#  Identifier  "DisplayLink"
#  Driver      "modesetting"
  Option      "PageFlip" "false"
EndSection
```
and it's better ... Not perfect, but better :)...

**Comment by AdnanHodzic** [comment]
@Tegaf thank you for the update, in next update I'll add these changes so once `displaylink-debian` detect user has an AMD card it will make these changes automatically for you.

I don't have an AMD card myself so I can't test how to make it better, but if you happen to discover anything else please let me know so I can add it to the installer.

**Comment by AdnanHodzic** [comment]
@Tegaf I'm about to changes to `displaylink-debian` could you please tell me what the output of `lspci -nnk | grep -i vga -A3 | grep 'in use'|cut -d":" -f2|sed 's/ //g'` is? Thanks!

**Comment by Tegaf** [comment]
@AdnanHodzic Output is "amdgpu"

**Comment by AdnanHodzic** [comment]
In latest commit, I've added code which will now allow "displaylink-debian" to automatically configure your Xorg config based on your graphics card. 

This feature may still be bit rough around the edges and might need some improvement. So if you have still have problems after pulling latest changes and running "re-install", please re-open this story and add output of following commands:

`cat /etc/X11/xorg.conf.d/20-displaylink.conf`
`lspci | grep -i vga`
`lspci -nnk | grep -i vga -A3 | grep 'in use'|cut -d":" -f2|sed 's/ //g'`
`lspci -nnk | grep -i vga -A3|grep Subsystem|cut -d" " -f5`

**Comment by Crashdummyy** [comment]
I am Facing the issues again #265 .
```sh
|14:11:36|crashdummy@CrashdummyEnvy:[Shared]> cat /etc/X11/xorg.conf.d/20-displaylink.conf
Section "Device"
    Identifier "AMDGPU"
    Driver     "amdgpu"
    Option     "PageFlip" "false"
EndSection
|14:11:44|crashdummy@CrashdummyEnvy:[Shared]> lspci | grep -i vga
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c3)
04:00.7 Non-VGA unclassified device: Advanced Micro Devices, Inc. [AMD] Device 15e4
|14:11:55|crashdummy@CrashdummyEnvy:[Shared]> lspci -nnk | grep -i vga -A3 | grep 'in use'|cut -d":" -f2|sed 's/ //g'
amdgpu
|14:12:02|crashdummy@CrashdummyEnvy:[Shared]> lspci -nnk | grep -i vga -A3|grep Subsystem|cut -d" " -f5
Ridge
[103c:8497]
SATA


```

**Comment by Crashdummyy** [comment]
If I switch to Wayland, these Symptoms are almost gone :)
