### ISSUE TITLE
[FIXED] Screen not working after simple install on Debian Buster/sid (Thinkpad P72, Asus MB169B+))

### ISSUE THREAD

**Issue by terabyte** [AdnanHodzic/displaylink-debian#188]
Hey all,

First off - THANKS VERY MUCH!  I really appreciate the work you've done to make this "just work".

My Thinkpad P72 is set to NVIDIA only mode and I successfully use multiple monitors all the time using arandr and xrandr.  I used your tool to install the driver, rebooted, and xrandr still did not show the monitor, though lsusb did (as "Displaylink").

I did some digging and found this documentation for archlinux:
https://wiki.archlinux.org/index.php/DisplayLink

One of the steps it suggested was running `xrandr --listproviders`, and the output matched what they suggested:
```
Provider 0: id: 0x246 cap: 0x1, Source Output crtcs: 4 outputs: 6 associated providers: 0 name:NVIDIA-0
Provider 1: id: 0x41 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
```
So I then tried the command they recommended:
```
$ xrandr --setprovideroutputsource 1 0
$ xrandr --listproviders
Providers: number : 2
Provider 0: id: 0x246 cap: 0x1, Source Output crtcs: 4 outputs: 6 associated providers: 1 name:NVIDIA-0
Provider 1: id: 0x41 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
$ xrandr 
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
DP-0 disconnected primary (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-2 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 382mm x 215mm
   1920x1080     60.02*+  48.03  
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 disconnected (normal left inverted right x axis y axis)
DVI-I-1-1 connected (normal left inverted right x axis y axis)
   1920x1080     60.01 +
   1280x1024     75.02    60.02  
   1366x768      60.00  
   1024x768      75.03    70.07    60.00  
   800x600       60.32    56.25  
   848x480       60.00  
   640x480       59.94  
```
After associating the providers, the displaylink screen shows up as `DVI-I-1-1`.  After that, I was able to control the monitor with xrandr/arandr and everything works great.

*facepalm* I was going to suggest adding this all to the documentation, but I see *it is already there* in the post-install-guide.md.  I'm a moron.  Maybe add mention/link to the post install guide from the main readme and/or have the installer say "Warning: Things might not work unless you follow the directions in the post install guide" after installing, for morons like me?

**Comment by AdnanHodzic** [comment]
@terabyte most welcome and glad to hear you figured it out on your own. Regarding documentation improvements, I believe I explained everything in https://github.com/AdnanHodzic/displaylink-debian/pull/189 which was related to this issue.

Also if you could do me a favor, could you please share your output of `sudo ./displaylink-debian.sh --debug` I want to compare your debug info with new refactored way xorg.conf for DisplayLink is setup depending on graphics card.

I'll close this issue now, but feel to re-open it if same issue is still around.
