### ISSUE TITLE
Kali Support mods & 1.1.68 release

### ISSUE THREAD

**Issue by glindner** [AdnanHodzic/displaylink-debian#21]
Thank you for this script! I am able to triple monitor my setup because of it, which is awesome!

I made changes to support Kali kali-rolling release and it installed nicely on the HP Pavilion Gaming Laptop (15t-bc000) I recently purchased with the StarTech Universal USB 3.0 Docking Station - Dual Video I have attached...

I added the following block in the distro_check after #Debian and before the else statement -

`# Kali`
`elif [ "$lsb" == "Kali" ];`
`then`
        `if [ $codename == "kali-rolling" ];`
        `then`
                `echo -e "\nPlatform requirements satisfied, proceeding ...\n"`
        `else`
        `message`
        `exit 1`
        `fi`

Release level 1.1.68, unfortunately labels some of the zip/run files with the old 1.1.62 release label, so I had to create a version_old value at the top of the script and change the version to the newer 1.1.68-

`version=1.1.68`
`version_old=1.1.62`

And modify a couple moves to rename the files appropriately so the script completed as needed -

after the unzip and before the chmod +x, I added:

`mv $driver_dir/displaylink-driver-${version_old}.run $driver_dir/displaylink-driver-${version}.run`

then I changed the following move command:

`mv displaylink-driver-${version}/ $driver_dir/displaylink-driver-${version}`

to:

`mv displaylink-driver-${version_old}/ $driver_dir/displaylink-driver-${version}`

I hope this is useful - cheers!
George

**Comment by AdnanHodzic** [comment]
In latest commit I've added support for Kali Linux (kali-rolling, 2016.2).

Please pull the latest version of debian-displaylink, and let me know if you still have any problems.
