### ISSUE TITLE
Parrot sec support

### ISSUE THREAD

**Issue by jf6921668** [AdnanHodzic/displaylink-debian#222]
Please add support for Parrot security

**Comment by AdnanHodzic** [comment]
Sure, could you please add output of following command: `sudo ./displaylink-debian.sh --debug`

**Comment by AdnanHodzic** [comment]
@jf6921668 JFYI, if I don't get the information I requested, I'll close this issue in new few days due to inactivity.

**Comment by jf6921668** [comment]
@AdnanHodzic one min ill get it for you

**Comment by jf6921668** [comment]
@AdnanHodzic im going to do a quick pull on ur new release and edit it to support parrot if it works ill let u know

**Comment by jf6921668** [comment]
it didnt work so here you go

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

cat: /sys/devices/evdi/version: No such file or directory
--------------- Linux system info ----------------

Distro: Parrot
Release: n/a
Kernel: 4.19.0-parrot1-13t-amd64

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: 

------------------ Graphics card -----------------

Vendor: i915
Subsystem: Processor
VGA: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display (rev 0e)
VGA (3D): 
X11 version: 1.20.3-1
X11 configs:

-------------------- Monitors --------------------

Providers: number : 1
Provider 0: id: 0x45 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 2 outputs: 4 associated providers: 0 name:modesetting

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------

**Comment by AdnanHodzic** [comment]
@jf6921668 support for Parrot added, try running reinstall and let me know if you're still experiencing same issue.
