### ISSUE TITLE
Request for Mint Cindy

### ISSUE THREAD

**Issue by c3x** [AdnanHodzic/displaylink-debian#242]
Hello.
Is it possible to add support for Mint Cindy?

Thx.
Bee.

--------------- Linux system info ----------------

Distro: LinuxMint
Release: cindy
Kernel: 4.9.0-8-amd64

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: 

------------------ Graphics card -----------------

Vendor: i915
Subsystem: [103c:84b2]
VGA: Intel Corporation Device 5916 (rev 02)
VGA (3D): 
X11 version: 1.19.2-1+deb9u5
X11 configs:

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: Datei oder Verzeichnis nicht gefunden
Contents:
 

-------------------- Monitors --------------------

Providers: number : 1
Provider 0: id: 0x44 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 2 associated providers: 0 name:modesetting

-------------------------------------------------------------------

**Comment by AdnanHodzic** [comment]
Changes added as part of last commit, please pull the changes and run install again.
