### ISSUE TITLE
Displays linked with the driver doesn't work with Redshift/F.lux/etc.

### ISSUE THREAD

**Issue by Darcidride** [AdnanHodzic/displaylink-debian#243]
I'm using the redshift equivalent integrated inside GNOME3 (i'm on Debian unstable)

```
$ gdm3 --version
GDM 3.30.1
```

I saw that the yellow filter (remove blue lights), isn't working on the display connected with the displaylink adapter & driver, i tested with the integrated gnome3 tool, redshift and f.lux, same issue.

**Comment by Barabazs** [comment]
You'd have to report this to redshift.
