### ISSUE TITLE
Update EVDI to 1.6.1 to support Linux Kernel 5.0 and 5.1

### ISSUE THREAD

**Issue by Luc45** [AdnanHodzic/displaylink-debian#280]
Currently when trying to install `displaylink-debian` on a Linux Kernel 5+, EVDI fails to build:

```
Installing driver version: 5.1

DisplayLink Linux Software 5.1.26 install script called: install
Distribution discovered: Ubuntu 18.04.2 LTS
Installing
Configuring EVDI DKMS module
Registering EVDI kernel module with DKMS
Building EVDI kernel module with DKMS
ERROR (code 3): Failed to build evdi/5.1.26. Consult /var/lib/dkms/evdi/5.1.26/build/make.log for details..
Adding udlfb to blacklist
Adding udl to blacklist
```

EVDI 1.6.1, [released on May 8 2019](https://github.com/DisplayLink/evdi/releases), supports Kernel 5.0 and 5.1. Updating EVDI to 1.6.1. results in a successful build.

However, the DisplayLink installer 5.1 uses a previous version of EVDI.

This is a request to add support for EVDI 1.6.1, thus, Linux Kernels 5.0 and 5.1

**Comment by Barabazs** [comment]
Issue is abandoned and not longer valid since the installer installs a more recent version of evdi.
