### ISSUE TITLE
No provider detected with Debian bullseye/testing

### ISSUE THREAD

**Issue by redcartel** [AdnanHodzic/displaylink-debian#296]
Debian testing on a Thinkpad T470, attempting to use an AOC I1659FWUX

xrandr output:

> xrandr --listproviders
> Providers: number : 0

Debug output:

> systemctl status displaylink
> 
> ● displaylink-driver.service - DisplayLink Driver Service
>    Loaded: loaded (/lib/systemd/system/displaylink-driver.service; enabled; vendor preset: enabled)
>    Active: active (running) since Fri 2019-08-23 13:36:48 EDT; 2min 12s ago
>   Process: 3817 ExecStartPre=/bin/sh -c modprobe evdi || (dkms install evdi/5.2.14 && modprobe evdi) (code=exited, status=0/SUCCESS)
>  Main PID: 3819 (DisplayLinkMana)
>     Tasks: 35 (limit: 4915)
>    Memory: 18.5M
>    CGroup: /system.slice/displaylink-driver.service
>            └─3819 /opt/displaylink/DisplayLinkManager
> 
> Aug 23 13:36:48 byzantium systemd[1]: Starting DisplayLink Driver Service...
> Aug 23 13:36:48 byzantium systemd[1]: Started DisplayLink Driver Service.

Disconnecting and then reconnecting the device produces the following in dmesg:

> [ 1427.614392] usb 2-1: USB disconnect, device number 4
> [ 1427.619501] evdi: [D] evdi_painter_disconnect:708 (dev=1) Disconnected from 00000000fb81bddf
> [ 1427.619508] evdi: [D] evdi_detect:96 (dev=-1) poll connector state: disconnected
> [ 1427.619561] evdi: [D] evdi_driver_postclose:144 (dev=-1) Process tries to close us, postclose
> [ 1427.619563] evdi: [I] Task 3829 (DesktopManagerE) of process 3819 (DisplayLinkMana)
> [ 1431.105920] usb 2-1: new SuperSpeed Gen 1 USB device number 5 using xhci_hcd
> [ 1431.127775] usb 2-1: New USB device found, idVendor=17e9, idProduct=ff0f, bcdDevice=31.04
> [ 1431.127780] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [ 1431.127783] usb 2-1: Product: E1659FWUX
> [ 1431.127785] usb 2-1: Manufacturer: DisplayLink
> [ 1431.127788] usb 2-1: SerialNumber: KHUG3JA000642
> [ 1441.500029] evdi: [D] evdi_painter_connect:629 (dev=-1) Process is trying to connect
> [ 1441.500031] evdi: [I] Task 4118 (DesktopManagerE) of process 4109 (DisplayLinkMana)
> [ 1441.500034] evdi: [D] evdi_painter_connect:679 (dev=1) Connected with 00000000a848b439
> [ 1441.500036] evdi: [D] evdi_detect:92 (dev=1) poll connector state: connected

My primary screen flickers for a moment when I do this.

(ins)$ sudo ./displaylink-debian.sh --debug

> No protocol specified
> Can't open display :0
> 
> -------------------------------------------------------------------
> 
> Starting Debug ...
> 
> Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y
> 
> Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y
> 
> --------------- Linux system info ----------------
> 
> Distro: Debian
> Release: bullseye
> Kernel: 4.19.0-5-amd64
> 
> ---------------- DisplayLink info ----------------
> 
> Driver version: 1.6.0+dfsg
> 5.2.14
> DisplayLink service status: up and running
> EVDI service version: 1.6.1
> 
> ------------------ Graphics card -----------------
> 
> Vendor: i915
> Subsystem: [HD
> VGA: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
> VGA (3D): 
> X11 version: 1.20.4-1
> X11 configs:
> 
> -------------- DisplayLink xorg.conf -------------
> 
> File: /etc/X11/xorg.conf.d/20-displaylink.conf
> cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No such file or directory
> Contents:
>  
> -------------------- Monitors --------------------
> 
> -------------------------------------------------------------------
> 
> Use this information when submitting an issue (http://bit.ly/2GLDlpY)
> 
> -------------------------------------------------------------------
> 

This is the same for any of the suggested Xorg.conf options.

**Comment by devujan** [comment]
On Bullseye with evdi 1.9.1 and kernel 5.10.26-1 I get
[   77.399153] evdi: [D] evdi_crtc_init:413 drm_crtc_init: 0 p000000000dedf4d6
[   77.399949] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   77.400744] evdi evdi.0: [drm] Cannot find any crtc or sizes
[   77.402867] evdi: [W] evdi_painter_send_update_ready_if_needed:706 Painter does not exist!
[   77.407206] [drm] Initialized evdi 1.9.1 20210126 for evdi.0 on minor 0
[   77.408026] evdi: [I] Evdi platform_device create
[   77.408898] evdi: [D] evdi_crtc_init:413 drm_crtc_init: 0 p00000000f68ea074
[   77.409670] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   77.410433] evdi evdi.1: [drm] Cannot find any crtc or sizes
[   77.411200] evdi: [W] evdi_painter_send_update_ready_if_needed:706 Painter does not exist!
[   77.411654] [drm] Initialized evdi 1.9.1 20210126 for evdi.1 on minor 1
[   77.413197] evdi: [I] Evdi platform_device create
[   77.414002] evdi: [D] evdi_crtc_init:413 drm_crtc_init: 0 p00000000314633ec
[   77.414777] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   77.415538] evdi evdi.2: [drm] Cannot find any crtc or sizes
[   77.416310] evdi: [W] evdi_painter_send_update_ready_if_needed:706 Painter does not exist!
[   77.416382] [drm] Initialized evdi 1.9.1 20210126 for evdi.2 on minor 2
[   77.418017] evdi: [I] Evdi platform_device create
[   77.418829] evdi: [D] evdi_crtc_init:413 drm_crtc_init: 0 p00000000a94bae34
[   77.419615] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   77.420393] evdi evdi.3: [drm] Cannot find any crtc or sizes
[   77.421214] evdi: [W] evdi_painter_send_update_ready_if_needed:706 Painter does not exist!

-> No way!
