### ISSUE TITLE
USB type C to VGA adapter

### ISSUE THREAD

**Issue by hoangnguyen7699** [AdnanHodzic/displaylink-debian#310]
Hi!
I am using Ubuntu 18.04 and my laptop is Acer aspire 5. I already have an external monitor through HDMI port. Now I want to add one more monitor using USB type C to VGA  or USB 3.0 to VGA adapter. Is it possible to do this using your software?
Thanks a lot!

**Comment by Barabazs** [comment]
Closing this issue due to a lack of details and inactivity.

Please reopen this issue if you have more details to share.
