### ISSUE TITLE
(EE) open /dev/fb0: No such file or directory

### ISSUE THREAD

**Issue by yepla** [AdnanHodzic/displaylink-debian#33]
Hello

I have install last version of displaylink-debian driver

In /etc/X11/xorg.conf.d i have create a file 52-displaylink:

Section "Screen"
        Identifier "Screen1"
        Device     "Card1"
        Monitor    "Monitor1"
EndSection

Section "Device"
        Identifier  "Card1"
        Driver      "displaylink"
	BusID	"USB"
        Option "fbdev" "/dev/fb0"
EndSection

Section "Monitor"
        Identifier "Monitor1"
EndSection

#################################

DisplayLink Manager Service is start !

And i have this error in Xorg log:

(EE) open /dev/fb0: No such file or directory

$ ls -al /dev/fb*
crw-rw---- 1 root video 29, 0 Oct 20 18:32 /dev/fb0

Result : 
My screen seems not respond like nothing is done (black screen)

I give you the result of xrandr --listproviders 
Providers: number : 1
Provider 0: id: 0x1ab cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting

Please help !

**Comment by AdnanHodzic** [comment]
I just made a bunch of updates to the tool. Could you please do the following:

1. git pull the latest version
2. run uninstall
3. reboot
4. install
5. reboot

I also suggest you remove that /etc/X11/xorg.conf.d/52-displaylink file, as it's completely redundant.

In case you're still experiencing problems after steps above, please re-open this issue, or create a new issue.
