### ISSUE TITLE
Add Linux Mint 19.3 Tricia as supported platform

### ISSUE THREAD

**Issue by Swaphelaer** [AdnanHodzic/displaylink-debian#330]
cat: /sys/devices/evdi/version: No such file or directory
--------------- Linux system info ----------------

Distro: LinuxMint
Release: tricia
Kernel: 5.3.0-24-generic

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: 

------------------ Graphics card -----------------

Vendor: i915
Subsystem: 
VGA: Intel Corporation Device 9b41 (rev 02)
VGA (3D): NVIDIA Corporation Device 1d13 (rev a1)
X11 version: 1.20.4-1ubuntu3~18.04.1
X11 configs:

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No such file or directory
Contents:
 

-------------------- Monitors --------------------

Providers: number : 2
Provider 0: id: 0x66 cap: 0x9, Source Output, Sink Offload crtcs: 3 outputs: 4 associated providers: 0 name:modesetting
Provider 1: id: 0x3f cap: 0x0 crtcs: 0 outputs: 0 associated providers: 0 name:modesetting

**Comment by AdnanHodzic** [comment]
As requested support for Linux Mint 19.3 Tricia has been added as part of c4be2f
