### ISSUE TITLE
unable to stretch single image to multiple displays

### ISSUE THREAD

**Issue by RudreshS** [AdnanHodzic/displaylink-debian#335]
As i connected 4 displays in daisy chain link and running the Qt application(which opens a window and fits to all displays automatically, working when displays connected to windows machine). but on linux(ubuntu) the Qt window is opening on the first display only.

**here is the configuration:**

--------------- Linux system info ----------------

Distro: Ubuntu
Release: bionic
Kernel: 5.0.0-32-generic

---------------- DisplayLink info ----------------

Driver version: 5.2.14
DisplayLink service status: up and running
EVDI service version: 1.6.1

------------------ Graphics card -----------------

Vendor: nouveau
Subsystem: Ltd.
VGA: NVIDIA Corporation GT218 [GeForce 210] (rev a2)
VGA (3D): 
X11 version: 1.20.4-1ubuntu3~18.04.1
X11 configs: /etc/X11/xorg.conf.d/20-displaylink.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "OutputClass"
    Identifier  "DisplayLink"
    MatchDriver "evdi"
    Driver      "modesetting"
    Option      "AccelMethod" "none"
EndSection

-------------------- Monitors --------------------

Providers: number : 5
Provider 0: id: 0xce cap: 0x9, Source Output, Sink Offload crtcs: 2 outputs: 3 associated providers: 4 name:modesetting
Provider 1: id: 0xa9 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0x87 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 3: id: 0x65 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 4: id: 0x41 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting

did i miss any configuration??

**Comment by Barabazs** [comment]
This doesn't seem to be related to the use of this installer.
