### ISSUE TITLE
(EE) FBDEV(0): FBIOPUTCMAP: Device or resource busy

### ISSUE THREAD

**Issue by yepla** [AdnanHodzic/displaylink-debian#34]
Hello

I have reinstall the displaylink driver but still have an issue :(

systemctl start dlm.service

systemctl status dlm.service
● dlm.service - DisplayLink Manager Service
   Loaded: loaded (/lib/systemd/system/dlm.service; static; vendor preset: enabl
   Active: active (running) since Fri 2016-10-21 13:08:12 CEST; 3min 48s ago
  Process: 4029 ExecStartPre=/sbin/modprobe evdi (code=exited, status=0/SUCCESS)
 Main PID: 4034 (DisplayLinkMana)
   CGroup: /system.slice/dlm.service
           └─4034 /opt/displaylink/DisplayLinkManager

Oct 21 13:08:12 desktop systemd[1]: Starting DisplayLink Manager Service...
Oct 21 13:08:12 desktop systemd[1]: Started DisplayLink Manager Service.

systemctl enable dlm.service
The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
4) In case of template units, the unit is meant to be enabled with some
   instance name specified.

xrandr --listproviders 
Providers: number : 1
Provider 0: id: 0x1ac cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting

On gnome:
gnome-control-center display
Not find my adapter :(

Buy using xorg.conf.DL file and .xinitrc Xorg.log say me:
(EE) FBDEV(0): FBIOPUTCMAP: Device or resource busy

I start to become crazy with this please help !

**Comment by AdnanHodzic** [comment]
Do what I asked you to do in other issue you reported: https://github.com/AdnanHodzic/displaylink-debian/issues/33

If you want me to help you, do what I asked you to do. If it doesn't work, for each action/step, please paste the output.

If you're still having same issue, please re-open this issue.
