### ISSUE TITLE
Allow a reboot for Reinstall script

### ISSUE THREAD

**Issue by robotard** [AdnanHodzic/displaylink-debian#381]
Currently, the reinstall script runs the standard uninstall function, but where EVDI requisites a reboot to remove from kernel, the install steps are not undertaken after the initial clean up. 

Todo- explore how to place a correct CTA for install function (or continue where reinstall left off) to be run as root after reboot has occurred...

**Comment by Barabazs** [comment]
For me the easiest workaround was to simply patch the reboot part of displaylink-installer.sh and let the displaylink-debian.sh prompt for the reboot at the end. #457 

You're welcome to pursue your initial idea if you have the time.
