### ISSUE TITLE
Fix resolution on booting - Debian Testing (5.4.19-1 (2020-02-13))

### ISSUE THREAD

**Issue by marcelolaia** [AdnanHodzic/displaylink-debian#387]
I am running Debian Bullseye (Testing) and I, finally, got my third monitor working! I'm very grateful to @AdnanHodzic .
The third monitor is a AOC 511Vwb 16:10 12080x800@60 DCR 1200:1. On boot, after GDM is loaded and is on login screen, it show: Input not supported. Immediately after login, the third monitor change message to Cable not connected.
On the Gnome Terminal, I need to run:
`xrandr --output DVI-I-2-1 --auto --right-of eDP-1`
So, the AOC monitor change message to "Input not supported".
On ARandR I see the AOC monitor on 1280x1024. To got it working, I need to change to 1280x720.
It's OK and very nice!
However, there is a method to got the AOC working on boot with the supported resolution? Without the command line adjustment above?
The `/etc/X11/xorg.conf.d/` is empty.
`$ xrandr --listproviders`
`Providers: number : 3`
`Provider 0: id: 0x44 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 2 associated providers: 1 name:modesetting`
`Provider 1: id: 0x10a cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting`
`Provider 2: id: 0xe8 cap: 0xd, Source Output, Source Offload, Sink Offload crtcs: 0 outputs: 0 associated providers: 0 name:AMD Radeon R7 M260 @ pci:0000:03:00.0`
Thank you so much!

**Comment by Barabazs** [comment]
This issue does not appear to be related to the use of this installer.
