### ISSUE TITLE
paypal donation link does not work 

### ISSUE THREAD

**Issue by polrus** [AdnanHodzic/displaylink-debian#390]
Hi
Wanted to donate but the link fails

**Comment by AdnanHodzic** [comment]
Hi, thank you for your support, much appreciated.

I've [updated the PayPal link](https://github.com/AdnanHodzic/displaylink-debian/blob/master/README.md#donate-paypal-or-bitcoin), please try again.

**Comment by AdnanHodzic** [comment]
@polrus I've updated the link again, I kept forcing it to be in English locally which made it expire each time.

Could you [please try with this updated one](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=adnan%40hodzic.org&item_name=Contribution+for+work+on+debian-displaylink&currency_code=EUR&source=url)?

I've also updated the [link in README](https://github.com/AdnanHodzic/displaylink-debian/blob/master/README.md#donate-paypal-or-bitcoin).

Thanks

**Comment by Barabazs** [comment]
I can confirm that the link works.

PS: please don't be offended by the amount.
