### ISSUE TITLE
Auto-Connect Display for Debian 10

### ISSUE THREAD

**Issue by thogaw** [AdnanHodzic/displaylink-debian#394]
Hi,

probably you want to integrate my solution for auto-enabling the display on debian buster. Probably the script has to be do some more checks and should not be fixed to the device-id but as a basis it works ;)

I have created a file `/etc/X11/Xsession.d/90displaylink` with content
```
$(xrandr --listproviders | grep -q "0x41") && xrandr --setprovideroutputsource 1 0
```

This works in my GDM3 Setup with disabled wayland support.

**Comment by Barabazs** [comment]
Thank you for your feedback. I'm unsure how this could be expanded into a "one script fits all"... You're always welcome to give it a try and submit a PR, but this looks way out of scope for this repo.
