### ISSUE TITLE
Linux Mint support

### ISSUE THREAD

**Issue by granteagon** [AdnanHodzic/displaylink-debian#4]
Is Linux Mint support possible?  What would need to happen in the code to make it work?  I'm willing to take a crack at in on my machine and do a pull-request if it works.

Thanks

**Comment by AdnanHodzic** [comment]
Only reason why Mint is not support is that it's not using systemd. If they make a switch to systemd in near future I'd be willing to extend this tool to Mint as well.

Until then, if you feel like give it a try, please feel free :)

**Comment by AdnanHodzic** [comment]
@granteagon could you please tell me which version of Mint are using?

**Comment by danielmanesku** [comment]
I manged to install the driver on Mint 18 Cinnamon. Downloaded if from official [website](http://www.displaylink.com/downloads/ubuntu), `chmod +x displaylink-driver-1.1.62.run && ./displaylink-driver-1.1.62.run`. After it was done `sudo systemctl start displaylink`, but I am not sure if this was needed, if it did anything at all.
That's it, it works now :)

**Comment by AdnanHodzic** [comment]
In latest commit I've added support for Mint Linux (sarah, rosa, petra, olivia).

Please pull the latest version of debian-displaylink, and let me know if you still have any problems.
