### ISSUE TITLE
Fatal error while installing: libdrm/drm.h

### ISSUE THREAD

**Issue by mr-tomtom** [AdnanHodzic/displaylink-debian#409]
While installing on a fresh 20.04 install I got the following error.

vdi_lib.c:6:10: fatal error: libdrm/drm.h: No such file or directory

I tried both method 1 and 2 for installation. Neither worked.

make[2]: Leaving directory '/usr/src/linux-headers-5.4.0-28-generic'
make[1]: Leaving directory '/home/tom/displaylink/evdi/module'
CFLAGS="-I../module -Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers " make -C library 
make[1]: Entering directory '/home/tom/displaylink/evdi/library'
cc -I../module -std=gnu99 -fPIC -I../module -Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers    -c -o evdi_lib.o evdi_lib.c
evdi_lib.c:6:10: fatal error: libdrm/drm.h: No such file or directory
    6 | #include <libdrm/drm.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: evdi_lib.o] Error 1
make[1]: Leaving directory '/home/tom/displaylink/evdi/library'
make: *** [Makefile:9: all] Error 2
cp: cannot stat '../library/libevdi.so.1.*': No such file or directory

**Comment by mr-tomtom** [comment]
Fixed with following:

sudo apt-get install libdrm-dev

**Comment by AdnanHodzic** [comment]
In last change I added `libdrm-dev` to be installed as dependency with `displaylink-debian`.
