### ISSUE TITLE
Clipping box around cursor

### ISSUE THREAD

**Issue by mnowotnik** [AdnanHodzic/displaylink-debian#412]
System: Kubuntu 20.04
Two monitor setup

Plugging second monitor into Dell D6000 causes a clipping box to appear behind cursor. Looks really glitchy and is extremely annoying.

This issue is probably caused by this bug: https://bugs.launchpad.net/ubuntu/+source/plasma-workspace/+bug/1684240 , so unrelated to displaylink-debian. I just made this issue as a reference.
It manifests itself when DisplayLink driver is used. 

Do you know any workaround?
What definitely works for me:

```
sudo service sddm restart
```

It's bothersome to log in twice, though, since this command logs out a user.

**Comment by mnowotnik** [comment]
Additionally, the issue doesn't appear when the system is booted in "Recovery Mode" for some reason.

**Comment by Barabazs** [comment]
Have you tried this [suggestion](https://support.displaylink.com/knowledgebase/articles/1843660-screen-freezes-after-opening-an-application-only)?

Your best bet is to file an issue [here](https://github.com/DisplayLink/evdi).

**Comment by mnowotnik** [comment]
I think I've installed official display link driver for Ubuntu 20 and the issue disappeared.
