### ISSUE TITLE
Failed installation on Debian Buster

### ISSUE THREAD

**Issue by salamonn** [AdnanHodzic/displaylink-debian#418]
Hi Adnan and anyone who might be able to help,

I'm fairly new to both Debian and Git so please forgive any faux pas in reporting bugs (just let me know what information to provide).
I followed the installation and the post-installation guide, but it seems not to have worked, since I get

`root@DebianMu:/home/nela# ./displaylink-debian.sh --debug`

-------------------------------------------------------------------
`Starting Debug ...
Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y
Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y
cat: /sys/devices/evdi/version: No such file or directory`
and

`root@DebianMu:/home/nela# DisplayLink info
bash: DisplayLink: command not found`

I ran `uname -a` and this is the system information it delivers:
`root@DebianMu:/home/nela# uname -a
Linux DebianMu 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux
`

While installing I also ran into this issue:

`Preparing for install`
`Archive:  DisplayLink_Ubuntu_5.3.1.zip`
`inflating: 5.3.1/displaylink-driver-5.3.1.34.run`
`Creating directory displaylink-driver-5.3.1.34`
`Verifying archive integrity...  100%   All good.`
`Uncompressing DisplayLink Linux Driver 5.3.1.34  100% `
`ln: failed to create symbolic link '/lib/modules/4.19.0-8-amd64/build/Kconfig': File exists`

I'd appreciate any help at all (and thank you for the work you've invested in this so far).

Update: I managed to use the solution suggested in https://github.com/AdnanHodzic/displaylink-debian/issues/410#issue-611357894 , however now I'm facing the problem of having to each time I start the computer run xrandr in order to get the monitor detected. So in case the displaylink-debian.sh circumvents this, I'd be really glad to use the Debian solution (I'm not a developer though, so my understanding of the differences is limited).

**Comment by salamonn** [comment]
The solution in https://github.com/AdnanHodzic/displaylink-debian/issues/410#issue-611357894 worked for me as well!

**Comment by salamonn** [comment]
Although the solution in #410 had worked and the monitor worked perfectly, after restarting I get a blank monitor. Any advice whatsoever would be highly appreciated.

**Comment by follettortuga** [comment]
See the [Post Installation Guide](https://github.com/AdnanHodzic/displaylink-debian/blob/master/post-install-guide.md), hotplug doesn't work on Debian. So if you already managed to install the official DisplayLink driver following [#410 ](https://github.com/AdnanHodzic/displaylink-debian/issues/410), the issue is resolved.

Also see my response to your question there.

**Comment by salamonn** [comment]
Thank you!
