### ISSUE TITLE
Black screen when change resolution to 1366x768

### ISSUE THREAD

**Issue by qman-web-development** [AdnanHodzic/displaylink-debian#419]
my configuration:
--------------- Linux system info ----------------

Distro: Ubuntu
Release: focal
Kernel: 5.4.0-29-generic

---------------- DisplayLink info ----------------

Driver version: 1.7.0
5.2.14
DisplayLink service status: up and running
EVDI service version: 1.7.0

------------------ Graphics card -----------------

Vendor: i915
Subsystem: [1028:096a]
VGA: Intel Corporation UHD Graphics (rev 02)
VGA (3D): 
X11 version: 1.20.8-2ubuntu2
X11 configs: /etc/X11/xorg.conf.d/20-displaylink.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
   Section "Device"
  Identifier "intel"
  Driver "modesetting"
  Option "AccelMethod" "None"
EndSection

-------------------- Monitors --------------------

Providers: number : 0

-------------------------------------------------------------------

**Comment by ScreamCZE** [comment]
Can you let me know what adapter/dock do you have? The latest DL-6950 chipset does not support this resolution, so this could be also a problem.

**Comment by Barabazs** [comment]
Issue does not appear to be related to the use of this installer.
