### ISSUE TITLE
External 2nd monitor don't work with 1920x1080 resolution

### ISSUE THREAD

**Issue by eyalmazuz** [AdnanHodzic/displaylink-debian#424]
I've installed the DisplayLink driver yesterday from the official source and everything was working fine, but for some reason today my 2nd external monitor gets a black screen when the resolution is set to 1920x1080, and also when it's that resolution, it makes the other external monitor (which works fine) to flicker and goes to black screen every few seconds.
when I change the resolution to 1280x1024, everything works fine without problems.
here's the debug output

edit: I tried locating the problem and it seems like the problem is in the connection between the monitor and the docking station.
I tried different screens and it worked
I tried connecting directly to the laptop and it works
I tried different cable but the monitor connected to the docking station and it doesn't work
the problem also persists on windows so it's not a Linux only problem
the monitor is lenovo l24e-20
the docking station is: wavlink wl-ug39dk3 rev 1.

```
--------------- Linux system info ----------------

Distro: Ubuntu
Release: focal
Kernel: 5.4.0-31-generic

---------------- DisplayLink info ----------------

Driver version: 1.7.0
DisplayLink service status: up and running
EVDI service version: 1.7.0

------------------ Graphics card -----------------

Vendor: i915
Subsystem: 630
VGA: Intel Corporation UHD Graphics 630 (Mobile)
VGA (3D): NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)
X11 version: 1.20.8-2ubuntu2
X11 configs: /etc/X11/xorg.conf /etc/X11/xorg.conf.d/20-displaylink.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "Device"
	Identifier "DisplayLink"
	Driver "modesetting"
	Option "PageFlip" "false"
EndSection

-------------------- Monitors --------------------

Providers: number : 6
Provider 0: id: 0x46 cap: 0x9, Source Output, Sink Offload crtcs: 3 outputs: 4 associated providers: 4 name:modesetting
Provider 1: id: 0x172 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0x150 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 3: id: 0x121 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 4: id: 0xf3 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 5: id: 0xd1 cap: 0x0 crtcs: 0 outputs: 0 associated providers: 0 name:modesetting

-------------------------------------------------------------------
```

**Comment by Barabazs** [comment]
This doesn't look like an error related to the use of this installer.
