### ISSUE TITLE
MX Linux 19.2 KDE x64 sysvinit?

### ISSUE THREAD

**Issue by TheBlogHouse** [AdnanHodzic/displaylink-debian#465]
Hey

I'm using 5.8 kernel on the above MX Linux and having tried installing my Display Link USB monitor using your latest version of these drivers and I'm not getting any output. When I run sudo ./displaylink-debian.sh --debug I get the following and jsut wondering if anyone else using sysvinit has got things working and has some tips?

--------------- Linux system info ----------------
Distro: Debian
Release: buster
Kernel: 5.8.0-2-amd64

---------------- DisplayLink info ----------------
Driver version: 1.7.0
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
DisplayLink service status: 
EVDI service version: 1.7.0

------------------ Graphics card -----------------
Vendor: amdgpu
Subsystem: Renoir
VGA: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev c6)
VGA (3D): 
X11 version: 1.20.4-1+deb10u1
X11 configs: /etc/X11/xorg.conf.d/synaptics.conf /etc/X11/xorg.conf.d/20-displaylink.conf /etc/X11/xorg.conf.d/10-evdev.conf

-------------- DisplayLink xorg.conf -------------
File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "Device"
  Identifier  "DisplayLink"
  Driver      "modesetting"
  Option      "PageFlip" "false"
EndSection

-------------------- Monitors --------------------
Providers: number : 5
Provider 0: id: 0xcd cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 4 outputs: 2 associated providers: 0 name:modesetting
Provider 1: id: 0xa7 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 2: id: 0x85 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 3: id: 0x63 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 4: id: 0x41 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting

Thanks for any help

**Comment by kngharv** [comment]
Instead of solving the problem, have you consider to get around it?  I thinks for MX Linux, there is an boot option to use systemd instead of sysVinit.

Try that first. 

(i am trying to figure this out myself as we speak)

**Comment by TheBlogHouse** [comment]
Yes I did but after many hours gave up, installed Kubuntu which has a newer version of Plasma by default, installed the latest 5.8.12 kernel using the great mainline app and the latest displaylink-driver-5.3.1.34 from Display link and all works well 👍

**Comment by kngharv** [comment]
1. what do you mean by "latest displaylink-driver 5.3.1.34?"  did you use this installation script?  or you download the driver directly?
2.  are you using X11 or wayland?  I am having the hardest problem get my external monitor detected when I am using X11.  I have tried this displaylink-debian script on 3 different distros and none of them can detect external monitor when Xorg is used.

**Comment by TheBlogHouse** [comment]
> 1. what do you mean by "latest displaylink-driver 5.3.1.34?"  did you use this installation script?  or you download the driver directly?
> 2. are you using X11 or wayland?  I am having the hardest problem get my external monitor detected when I am using X11.  I have tried this displaylink-debian script on 3 different distros and none of them can detect external monitor when Xorg is used.

I answered above but maybe see https://www.displaylink.org/forum/showpost.php?p=90773&postcount=106 for context
