### ISSUE TITLE
Displaylink Kali Linux

### ISSUE THREAD

**Issue by volkpa99** [AdnanHodzic/displaylink-debian#485]
Hello,

I have the HP USB-C Universal Dock.
With Windows it works without problems and everything is transferred. 
Now I have a Linux computer Thinkpad T450s, Kali Linux (5.7.0-kali1-amd64, Release: 2020.3) is installed.

The mouse and keyboard, ethernet is transferred, unfortunately only no display on the external monitors. (Monitors remain black)
In addition I read that the DisplayLink driver must be installed?
If I install it successfully via your script(docking station is connected) then the computer will not start properly if the docking station is not connected.
The PC then hangs in boot mode, only if the docking station is connected, the PC will boot up to the login screen.

```
Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

cat: /sys/devices/evdi/version: File or directory not found
```

Why can't I run the debug?
I don't have the following file either: /etc/X11/xorg.conf.d/20-displaylink.conf
what am I doing wrong? 

Can you help me? Thanks for the support

Greetings

**Comment by volkpa99** [comment]
root@kali:/home/volkpa/Downloads/DisplayLink/displaylink-debian# ./displaylink-debian.sh --debug

-------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

cat: /sys/devices/evdi/version: Datei oder Verzeichnis nicht gefunden
root@kali:/home/volkpa/Downloads/DisplayLink/displaylink-debian# xrandr --listproviders
Providers: number : 1
Provider 0: id: 0x47 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 5 associated providers: 0 name:modesetting
root@kali:/home/volkpa/Downloads/DisplayLink/displaylink-debian#


what am I doing wrong?

**Comment by Barabazs** [comment]
Can you run the install script and post the output here?
The install did not succeed, hence the debug error.

**Comment by volkpa99** [comment]
Hi,
I have downloaded and installed everything again. After that it worked, the issue can be closed.
Thanks a lot!
