### ISSUE TITLE
Please, add the requirements

### ISSUE THREAD

**Issue by canepan** [AdnanHodzic/displaylink-debian#486]
I am trying to run the `displaylink-debian.sh` script on my Debian, but so far it fails finding:
* lspci (pkg pciutils on debian)
* xrandr: I am running it as a text-only server, but having a display from time to time would be useful (pkg x11-xserver-utils on debian)

It also requires to be run from an X console, since xrandr looks for a DISPLAY

Thank you!

**Comment by Barabazs** [comment]
Your use case is too niche for this project. You'll have to proceed package by package.

**Comment by canepan** [comment]
I thought mentioning it in the README would help more users and wouldn't be a big effort.

Thank you any way

**Comment by Barabazs** [comment]
It looks like I misunderstood your issue.

Do you mean that those are the only packages needed when starting from scratch?

**Comment by canepan** [comment]
By looking at how the "globalvars" are populated, it looks like that

**Comment by Barabazs** [comment]
Thank you for your feedback. I'll add pciutils to the dependencies. 
x11-xserver-utils was already part of the dependencies.
