### ISSUE TITLE
Displaylink is not work properly on Ubuntu 16.10

### ISSUE THREAD

**Issue by vladrulez** [AdnanHodzic/displaylink-debian#49]
I have removed Displaylink drivers, upgraded my Ubuntu 16.04 installation from 16.04 to 16.10 and installed the drivers again.
Unfortunately they want work properly on 16.10. Only static images could used on external monitor.

$ uname -a
Linux 4.8.0-32-generic #34-Ubuntu SMP Tue Dec 13 14:30:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ systemctl list-units |grep -i link
dlm.service                                                                               loaded active running   DisplayLink Manager Service

Any thoughts?

**Comment by vladrulez** [comment]
The problem was related to Intel video drivers for I7 internal video. I have uninstalled DisplayLink drivers, switched main video driver to Nvidia GeForce GTX 960M, installed DisplayLink drivers again and they start to work normally as they worked on Ubuntu 16.04.
Thank you for your patience.

**Comment by jkldgoefgkljefogeg** [comment]
Displaylink with 3rd gen Intel Graphics was working on 16.04. After upgrading to 16.10

- Chrome and some other apps are extremely slow on Displaylink screen (fine on other screens)
- xserver error every time I reboot. Have to use default config every time
- screen layout needs to be reconfigured on every reboot (probably related to the default x config on every reboot)
- cursor flickering issue is back, it is getting quite bad
- incorrect screen size when using Gnome, the total screen size created is smaller than actual screen size

**Comment by AdnanHodzic** [comment]
I think what you described here is related to upstream, and I suggest[ reporting this problem there](https://github.com/DisplayLink/evdi).

It's also possible that something went wrong with upgrade to 16.10. I have one computer running on 16.04 with 16.10 kernel (4.8.x) and everything works just fine.
