### ISSUE TITLE
MX Linux 19.3, Kernel 5.8.0-3-amd64 on Thinkpad L480 with Intel® UHD 620 Graphics

### ISSUE THREAD

**Issue by hashguru** [AdnanHodzic/displaylink-debian#517]
Tried all the suggestions so far, nothing worked. I have the Thinkpad USB 3.0 dock connected to my L480. Fresh install of MX linux with KDE. Legacy only boot with UEFI and secure boot disabled. Set to boot with SYSTEMD and X11. 

Two screens connected to the dock just remain black after hours of fiddling.
I am sure it is going to work, but my limited understanding of what to do next forces me to ask for help.

here follows the debug after fresh install of displaylink-debian to start the thread:

-------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

--------------- Linux system info ----------------

Distro: Debian
Release: buster
Kernel: 5.8.0-3-amd64

---------------- DisplayLink info ----------------

Driver version: 1.7.2
DisplayLink service status: up and running
EVDI service version: 1.7.2

------------------ Graphics card -----------------

Vendor: i915
Subsystem: 620
VGA: Intel Corporation UHD Graphics 620 (rev 07)
VGA (3D): 
X11 version: 1.20.9-2~mx19ahs+1
X11 configs: /etc/X11/xorg.conf.d/20-displaylink.conf /etc/X11/xorg.conf.d/synaptics.conf /etc/X11/xorg.conf.d/10-evdev.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "OutputClass"
    Identifier  "DisplayLink"
    MatchDriver "evdi"
    Driver      "modesetting"
    Option      "AccelMethod" "none"
EndSection

-------------------- Monitors --------------------

Providers: number : 5
Provider 0: id: 0x47 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 5 associated providers: 4 name:modesetting
Provider 1: id: 0x13f cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0x11d cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 3: id: 0xfb cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 4: id: 0xd9 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting

-------------------------------------------------------------------

**Comment by Barabazs** [comment]
You have to associate the providers. Try this procedure: https://github.com/AdnanHodzic/displaylink-debian/blob/master/post-install-guide.md#display-detection

**Comment by hashguru** [comment]
i did try that, and many other things from closed issues. no go. i edited the original post to include the debug after associating providers.

**Comment by Barabazs** [comment]
I would try to remove these files and see if it works after rebooting.
Don't forget to make a backup of them.

 /etc/X11/xorg.conf.d/synaptics.conf 
/etc/X11/xorg.conf.d/10-evdev.conf

**Comment by hashguru** [comment]
Removed the files. Rebooted system. Associated providers. Display still black as night.
