### ISSUE TITLE
Installation of displaylink-driver-5.3.1.34 fails for Linux Mint 20 Ulyana with dkms error "Invalid number of arguments passed"

### ISSUE THREAD

**Issue by KiAchim** [AdnanHodzic/displaylink-debian#520]
Im following steps in the [displaylink forum](https://displaylink.org/forum/showpost.php?p=91259&postcount=19)
I used [evdi tag 1.9.0](https://github.com/DisplayLink/evdi/tags)
Line 28 of  displaylink-installer.sh fails with "Error! Invalid number of arguments passed."
My system is
System:    Kernel: 5.4.0-58-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal

**Comment by Barabazs** [comment]
Your issue is unrelated to displaylink-debian.

**Comment by KiAchim** [comment]
Sorry for that.
