### ISSUE TITLE
Unsatisfied dependencies. Missing component: DKMS.

### ISSUE THREAD

**Issue by Graham-King** [AdnanHodzic/displaylink-debian#522]
Debian Buster does not have /usr/sbin in $PATH when switching to root using `su` but `su -` works.

displaylink-installer.sh references `dkms` several times but the binary is not found. I created an updated patch for displaylink-installer.sh to work around the issue.

### resources/displaylink-installer.patch
```
--- displaylink-installer.sh    2021-01-06 21:08:37.710447227 -0700
+++ displaylink-installer.sh    2021-01-06 21:07:23.958300737 -0700
@@ -2,6 +2,8 @@
 # Copyright (c) 2015 - 2020 DisplayLink (UK) Ltd.
 
 export LC_ALL=C
+export PATH=$PATH:/usr/sbin
+
 SELF=$0
 COREDIR=/opt/displaylink
 LOGSDIR=/var/log/displaylink
@@ -457,11 +459,11 @@
   echo "http://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu"
 
   echo -e "\nInstallation complete!"
-  echo -e "\nPlease reboot your computer if intending to use Xorg."
-  $XORG_RUNNING || exit 0
-  read -p 'Xorg is running. Do you want to reboot now? (Y/n)' CHOICE
-  [[ ${CHOICE:-Y} =~ ^[Nn]$ ]] && exit 0
-  reboot
+  #echo -e "\nPlease reboot your computer if intending to use Xorg."
+  #$XORG_RUNNING || exit 0
+  #read -p 'Xorg is running. Do you want to reboot now? (Y/n)' CHOICE
+  #[[ ${CHOICE:-Y} =~ ^[Nn]$ ]] && exit 0
+  #reboot
 }
 
 uninstall()
```

Upon completion the `reboot` command in displaylink-debian.sh failed for the same reason. I suggest adding `export PATH=$PATH:/usr/sbin` to displaylink-debian.sh as well. Or prevent the script from running if `dkms` is not executable within $PATH of the current user with a suggestion to use `su -` or `sudo -i` or `sudo -i` instead (I didn't test any of those approaches but they _should_ also work).

More info: https://wiki.debian.org/NewInBuster
> The su command in buster is provided by the util-linux source package, instead of the shadow source package, and no longer alters the PATH variable by default. This means that after doing su, your PATH may not contain directories like /sbin, and many system administration commands will fail. There are several workarounds:

wontfix: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918754

**Comment by Barabazs** [comment]
displaylink-debian should only be executed with sudo.
Other ways are not supported.
