### ISSUE TITLE
High CPU load on videos

### ISSUE THREAD

**Issue by maniac-0s** [AdnanHodzic/displaylink-debian#530]
I notice a high CPU load when watching videos on Firefox or Chrome over displaylink.

Also when I add my displays to the output and then close the lid display of my ThinkPad, everything becomes slow responding, taking like half a second to open desktop menus. I will have to go to xfce4 display setting and enable the internal display.

Then it runs more smooth again however scrolling in Firefox ect is a little "gluey", it doesn't stutter just scrolls less fluent than without displaylink. Watching videos (FullHD) causes the fan to turn on (never happens on just the internal display) and systemload increasing.

Debug output before association (I use "xrandr --setprovideroutputsource 3 0; xrandr --setprovideroutputsource 4 0" to associate displays):

`-------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

--------------- Linux system info ----------------

Distro: Debian
Release: bullseye
Kernel: 5.10.0-1-amd64

---------------- DisplayLink info ----------------

Driver version: 1.7.2
DisplayLink service status: up and running
EVDI service version: 1.7.2

------------------ Graphics card -----------------

Vendor: i915
Subsystem: 620
VGA: Intel Corporation UHD Graphics 620 (Whiskey Lake)
VGA (3D): 
X11 version: 1.20.10-2
X11 configs: /etc/X11/xorg.conf.d/20-displaylink.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "OutputClass"
    Identifier  "DisplayLink"
    MatchDriver "evdi"
    Driver      "modesetting"
    Option      "AccelMethod" "none"
EndSection

-------------------- Monitors --------------------

Providers: number : 5
Provider 0: id: 0x46 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 4 associated providers: 0 name:modesetting
Provider 1: id: 0x15c cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 2: id: 0x13a cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 3: id: 0x115 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 4: id: 0xd4 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------`

![Screenshot_2021-01-26_09-06-21](https://user-images.githubusercontent.com/78015362/105817983-a01eed00-5fb6-11eb-8daf-4d2ee3212ce4.png)

**Comment by Barabazs** [comment]
> Also when I add my displays to the output and then close the lid display of my ThinkPad, everything becomes slow responding, taking like half a second to open desktop menus. I will have to go to xfce4 display setting and enable the internal display.

This is a known issue. More info here: https://github.com/AdnanHodzic/displaylink-debian/issues/393#issuecomment-687780756

 
> Then it runs more smooth again however scrolling in Firefox ect is a little "gluey", it doesn't stutter just scrolls less fluent than without displaylink. Watching videos (FullHD) causes the fan to turn on (never happens on just the internal display) and systemload increasing.

Can't help you with that here. It's unrelated to the displaylink-debian installer.
You could try to turn off hardware acceleration in Firefox. Or maybe add   Option `"PageFlip" "false"` to your config.
