### ISSUE TITLE
Unit dlm.service entered failed state

### ISSUE THREAD

**Issue by FlavioOliveiraSilva** [AdnanHodzic/displaylink-debian#54]
Hello guys!

I am having problems to start the display link service. Everything went fine after installation but entered in a failed stated. I read somewhere here that UEFI maybe should be disabled to solve it. But I have no clue how to do it. Could anyone help me, please?
See log below. 

> systemctl status dlm.service
> dlm.service - DisplayLink Manager Service
   Loaded: loaded (/lib/systemd/system/dlm.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2017-01-28 13:52:28 CET; 3s ago
  Process: 2844 ExecStart=/opt/displaylink/DisplayLinkManager (code=exited, status=1/FAILURE)
  Process: 2842 ExecStartPre=/sbin/modprobe evdi (code=exited, status=0/SUCCESS)
 Main PID: 2844 (code=exited, status=1/FAILURE)
Jan 28 13:52:28 debian systemd[1]: Unit dlm.service entered failed state

**Comment by AdnanHodzic** [comment]
@FlavioOliveiraSilva please see [this issue ](https://github.com/AdnanHodzic/displaylink-debian/issues/15#issuecomment-280824050).
