### ISSUE TITLE
Off-by-one Supported platforms Debian Version

### ISSUE THREAD

**Issue by mxjeff** [AdnanHodzic/displaylink-debian#540]
Hi, 

Version for Debian are:

  * Stretch 9
  * Buster 10 (the current stable in 02/2021).
  * Bullseye 11

Please refer to https://www.debian.org/releases/

**Comment by Barabazs** [comment]
Please post the output of `sudo ./displaylink-debian.sh --debug`

**Comment by mxjeff** [comment]
Sorry my post was not explicit. I'm referring to README.md. [Debian version mentioned](https://github.com/AdnanHodzic/displaylink-debian#supported-platforms-are) are wrong.

**Comment by Barabazs** [comment]
I don't see what's wrong...
```
Supported platforms are:

    Debian: Jessie 8.0/Stretch 9.0/Buster 10/Bullseye (testing)/Sid (unstable)
```

**Comment by mxjeff** [comment]
Lack of caffeine on my side… Sorry for the noise /o\
