### ISSUE TITLE
support for Deepin 20.1 

### ISSUE THREAD

**Issue by ifromano** [AdnanHodzic/displaylink-debian#541]
I run the command in debug mode and this is the result

It will be possible to have support for this version of Deepin

--------------- Linux system info ----------------

Distro: Deepin
Release: n/a
Kernel: 5.10.5-amd64-desktop+

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: i915
Subsystem: E3-1200
VGA: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller (rev 09)
VGA (3D): 
X11 version: 1.20.4.10-1+eagle
X11 configs: /etc/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/75-wacom.conf /etc/X11/xorg.conf.d/50-synaptics.conf /etc/X11/xorg.conf.d/20-nvidia.conf /etc/X11/imwheel/startup.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No existe el fichero o el directorio
Contents:
 

-------------------- Monitors --------------------

Providers: number : 1
Provider 0: id: 0x44 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 2 associated providers: 0 name:modesetting

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------

**Comment by Barabazs** [comment]
Please retry with the latest version.
