### ISSUE TITLE
Night light does not work for Debian 11

### ISSUE THREAD

**Issue by yuelinn** [AdnanHodzic/displaylink-debian#547]
Hey, 

Firstly, thanks for the package. I managed to install displaylink on debian bullseye with no problem :+1: 

However, the night light does not work on the monitor using displaylink. The night light works fine on my laptop screen though. Not sure if this is a problem with the displaylink driver or with the way GNOME implemented the night light?

Any insight is much welcomed. Thanks!

**Comment by Barabazs** [comment]
This unrelated to displaylink-debian.

But I can tell you that it's not possible right now. 
You can find some information here: https://github.com/jonls/redshift/issues/311#issuecomment-477014037
