### ISSUE TITLE
Issue with parrot 5.10 with kernel 5.7

### ISSUE THREAD

**Issue by jruedaq** [AdnanHodzic/displaylink-debian#558]
--------------- Linux system info ----------------

Distro: Parrot
Release: n/a
Kernel: 5.7.0-2parrot2-amd64

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: amdgpu
Subsystem: Raven
VGA: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c4)
VGA (3D): NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
X11 version: 1.20.8-2
X11 configs: /etc/X11/xorg.conf.d/00-keyboard.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No existe el fichero o el directorio
Contents:
 

-------------------- Monitors --------------------

Providers: number : 2
Provider 0: id: 0x55 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 4 outputs: 2 associated providers: 0 name:Unknown AMD Radeon GPU @ pci:0000:04:00.0
Provider 1: id: 0x97 cap: 0x5, Source Output, Source Offload crtcs: 0 outputs: 0 associated providers: 0 name:modesetting

-------------------------------------------------------------------

**Comment by Barabazs** [comment]
Hi. Can you post the output of `sudo ./displaylink-debian.sh --install`

**Comment by jruedaq** [comment]
i install Parrot 5.11 and this is output

`
-------------------------------------------------------------------

Checking dependencies

unzip is installed
linux-headers-5.10.0-5parrot1-amd64 is installed
dkms is installed
lsb-release is installed
linux-source is installed
x11-xserver-utils is installed
wget is installed
libdrm-dev is installed
libelf-dev is installed
git is installed
pciutils is installed

Platform requirements satisfied, proceeding ...

-------------------------------------------------------------------

Please read the Software License Agreement available at: 
https://www.synaptics.com/node/3751?filetype=exe
Do you accept?: [Y/n]: 

Downloading DisplayLink Ubuntu driver:

--2021-04-06 15:21:21--  https://www.synaptics.com/sites/default/files/exe_files/2021-04/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu5.4-EXE.zip
Resolviendo www.synaptics.com (www.synaptics.com)... 52.36.27.145, 52.11.184.137
Conectando con www.synaptics.com (www.synaptics.com)[52.36.27.145]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 14501284 (14M) [application/zip]
Grabando a: «DisplayLink_Ubuntu_5.4.zip»

DisplayLink_Ubuntu_5.4.zip                                 100%[========================================================================================================================================>]  13,83M  5,34MB/s    en 2,6s    

2021-04-06 15:21:24 (5,34 MB/s) - «DisplayLink_Ubuntu_5.4.zip» guardado [14501284/14501284]

Removing prior: "5.4" directory

-------------------------------------------------------------------

Preparing for install

Archive:  DisplayLink_Ubuntu_5.4.zip
  inflating: 5.4/displaylink-driver-5.4.0-55.153.run  
Creating directory displaylink-driver-5.4.0-55.153
Verifying archive integrity...  100%   All good.
Uncompressing DisplayLink Linux Driver 5.4.0-55.153  100%  

-------------------------------------------------------------------
Clonando en 'evdi'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 46 (delta 2), reused 8 (delta 0), pack-reused 0
Recibiendo objetos: 100% (46/46), 68.00 KiB | 740.00 KiB/s, listo.
Resolviendo deltas: 100% (2/2), listo.
CFLAGS="-Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers" make -C module 
make[1]: se entra en el directorio '/home/jruedaq/displaylink-debian/evdi/module'
cat: /etc/redhat-release: No existe el fichero o el directorio
make -C /lib/modules/5.10.0-5parrot1-amd64/build M=$PWD
make[2]: se entra en el directorio '/usr/src/linux-headers-5.10.0-5parrot1-amd64'
cat: /etc/redhat-release: No existe el fichero o el directorio
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi_drv.o
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi_modeset.o
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi_connector.o
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi_encoder.o
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi_main.o
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi_fb.o
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi_gem.o
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi_painter.o
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi_params.o
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi_cursor.o
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi_debug.o
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi_ioc32.o
  LD [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi.o
cat: /etc/redhat-release: No existe el fichero o el directorio
  MODPOST /home/jruedaq/displaylink-debian/evdi/module/Module.symvers
  CC [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi.mod.o
  LD [M]  /home/jruedaq/displaylink-debian/evdi/module/evdi.ko
make[2]: se sale del directorio '/usr/src/linux-headers-5.10.0-5parrot1-amd64'
make[1]: se sale del directorio '/home/jruedaq/displaylink-debian/evdi/module'
CFLAGS="-I../module -Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers " make -C library 
make[1]: se entra en el directorio '/home/jruedaq/displaylink-debian/evdi/library'
cc -I../module -std=gnu99 -fPIC -I../module -Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers    -c -o evdi_lib.o evdi_lib.c
cc evdi_lib.o -shared -Wl,-soname,libevdi.so.0 -o libevdi.so.1.7.2 -lc -lgcc 
cp libevdi.so.1.7.2 libevdi.so
make[1]: se sale del directorio '/home/jruedaq/displaylink-debian/evdi/library'
patching file 5.4/displaylink-driver-5.4/displaylink-installer.sh
Hunk #1 FAILED at 457.
1 out of 1 hunk FAILED -- saving rejects to file 5.4/displaylink-driver-5.4/displaylink-installer.sh.rej
`

this is a `displaylink-installer.sh.rej`
`
--- /opt/displaylink/displaylink-installer.sh
+++ /opt/displaylink/displaylink-installer.sh
@@ -457,11 +457,11 @@
   echo "http://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu"

   echo -e "\nInstallation complete!"
-  echo -e "\nPlease reboot your computer if intending to use Xorg."
-  $XORG_RUNNING || exit 0
-  read -p 'Xorg is running. Do you want to reboot now? (Y/n)' CHOICE
-  [[ ${CHOICE:-Y} =~ ^[Nn]$ ]] && exit 0
-  reboot
+  #echo -e "\nPlease reboot your computer if intending to use Xorg."
+  #$XORG_RUNNING || exit 0
+  #read -p 'Xorg is running. Do you want to reboot now? (Y/n)' CHOICE
+  #[[ ${CHOICE:-Y} =~ ^[Nn]$ ]] && exit 0
+  #reboot
 }

 uninstall()

`

**Comment by jruedaq** [comment]
-------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

--------------- Linux system info ----------------

Distro: Parrot
Release: n/a
Kernel: 5.10.0-5parrot1-amd64

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: amdgpu
Subsystem: Raven
VGA: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c4)
VGA (3D): NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
X11 version: 1.20.10-3
X11 configs: /etc/X11/xorg.conf.d/00-keyboard.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No existe el fichero o el directorio
Contents:
 

-------------------- Monitors --------------------

Providers: number : 2
Provider 0: id: 0x55 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 4 outputs: 2 associated providers: 0 name:AMD Radeon(TM) Vega 8 Graphics @ pci:0000:04:00.0
Provider 1: id: 0x97 cap: 0x5, Source Output, Source Offload crtcs: 0 outputs: 0 associated providers: 0 name:modesetting

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------

**Comment by Barabazs** [comment]
Please try again with the latest version from git.

**Comment by jruedaq** [comment]
![20210424_140434.jpg](https://user-images.githubusercontent.com/24756521/115970108-08259680-a506-11eb-8b5f-dc676c3df362.jpg) after install and reboot the system show this `[0.858587] Bluetooth: hci0: Reading features failed (-16)`. In this moment my solution is reinstall Parrot 5.11

**Comment by jruedaq** [comment]
I test again, xorg not start, i try with startx but this no launch correctly
