### ISSUE TITLE
DisplayLink Driver Update Released on April 6th, 2021 to version: 5.4

### ISSUE THREAD

**Issue by mcoyle1960** [AdnanHodzic/displaylink-debian#564]
Currently, thanks to your work, DisplayLink is working on Ubuntu 20.10. I have occasional flashes, but no worse than under Windows. 

Now we have a new installer. Should I:
1. Don't update. Sit tight and wait for 21.04 installer release
2. Update using the standard DisplayLink 5.4 installer
3. Update to version 5.4 using displaylink-debian

Thanks!

**Comment by Barabazs** [comment]
Nobody can tell you what you should do. It's really up to you...
