### ISSUE TITLE
Im having an issue with gpu recognition in ubuntu

### ISSUE THREAD

**Issue by a1058090** [AdnanHodzic/displaylink-debian#568]
Im having issues with UBUNTU recognizing my GPU a GTX 950M.
In the about portion it reads "Mesa Intel® HD Graphics 530 (SKL GT2)" under the graphics portion.
I have already gone into additional drivers and set it to the nvidia driver. I even went into nvidia settings and selected nvidia as prime. Anyone have any idea?

**Comment by Barabazs** [comment]
This has nothing to do with displaylink-debian.
