### ISSUE TITLE
Support Request for debian based Nitrux Linux 1.4

### ISSUE THREAD

**Issue by miklit02** [AdnanHodzic/displaylink-debian#576]
--------------- Linux system info ----------------

Distro: Nitrux
Release: nitrux
Kernel: 5.10.33-051033-generic

---------------- DisplayLink info ----------------

Driver version: 
ERROR:systemctl:Unit displaylink-driver.service could not be found.
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: amdgpu
Subsystem: Device
VGA: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne (rev c2)
VGA (3D): 
X11 version: 1.20.11-1
X11 configs: /etc/X11/xorg.conf.d/00-keyboard.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: Datei oder Verzeichnis nicht gefunden
Contents:
 

-------------------- Monitors --------------------

Providers: number : 0

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------

Please give this relatively new distribution support of the displaylink driver. Thank you for your effort!
github-user: miklit02

**Comment by Barabazs** [comment]
Please try again with the latest changes.
