### ISSUE TITLE
Modesetting

### ISSUE THREAD

**Issue by lucaorioli** [AdnanHodzic/displaylink-debian#601]
Sorry to reopen but I haven't explained well in first issue, sorry.
I'm asking how to disable modesetting in displaylink driver, if I disable it at kernel level (adding nomodeset kernel parameter) displaylink doesn't work. But I need to disable modesetting to let my integrated screen works.

Thanks
Luca Orioli

**Comment by Barabazs** [comment]
Please don't open a new issue when you could reopen your first one. I'll close this and we can continue in the original issue.

Duplicate of #599
