### ISSUE TITLE
HP DV6 - having dual graphics was interchangeable when still using Windows 7

### ISSUE THREAD

**Issue by kurtborg92** [AdnanHodzic/displaylink-debian#603]
Hi I am trying to use a Targus USB3 Universal Dock, I got the usb and ethernet to work but the display is still not being displayed to date maybe you can help me with this. I tried all of the solutions you gave in the post-installation and even removed the conf file and re-created it again using different settings but it is still not working.

Any help will be greatly appreciated.

Thanks,
Kurt

--------------- Linux system info ----------------

Distro: Debian
Release: buster
Kernel: 4.19.0-17-amd64

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: i915
Subsystem: Processor
Radeon
VGA: Intel Corporation Core Processor Integrated Graphics Controller (rev 02)
Advanced Micro Devices, Inc. [AMD/ATI] Madison [Mobility Radeon HD 5650/5750 / 6530M/6550M]
VGA (3D): 
X11 version: 1.20.4-1+deb10u3
X11 configs: /etc/X11/xorg.conf.d/synaptics.conf /etc/X11/xorg.conf.d/20-displaylink.conf /etc/X11/xorg.conf.d/10-evdev.conf /etc/X11/xorg.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "Device"
    Identifier  "DisplayLink"
    Driver      "modesetting"
    Option      "PageFlip" "false"
EndSection

-------------------- Monitors --------------------

Providers: number : 1
Provider 0: id: 0x43 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 2 outputs: 2 associated providers: 0 name:modesetting

-------------------------------------------------------------------

**Comment by Barabazs** [comment]
Please try to reinstall and post the output of the installer, and then also the debug output.

**Comment by kurtborg92** [comment]
Hi Barabazs,

Re-Installer Output:

--------------------------- displaylink-debian -------------------------------

DisplayLink driver installer for Debian and Ubuntu based Linux distributions:

* Debian, Ubuntu, Elementary OS, Mint, Kali, Deepin and many more!
* Full list of all supported platforms: http://bit.ly/2zrwz2u
* When submitting a new issue, include Debug information

Options:

[I]nstall
[D]ebug
[R]e-install
[U]ninstall
[Q]uit

Select a key: [i/d/r/u/q]: r

-------------------------------------------------------------------

Checking dependencies

unzip is installed
linux-headers-4.19.0-17-amd64 is installed
dkms is installed
lsb-release is installed
linux-source is installed
x11-xserver-utils is installed
wget is installed
libdrm-dev is installed
libelf-dev is installed
git is installed
pciutils is installed

Platform requirements satisfied, proceeding ...

-------------------------------------------------------------------

Uninstalling ...

DisplayLink Linux Software 5.4.0-55.153 install script called: uninstall
Distribution discovered: Debian GNU/Linux 10 (buster)

Uninstalling

[ Removing EVDI from kernel tree, DKMS, and removing sources. ]
dkms remove evdi/1.9.1 --all

-------- Uninstall Beginning --------
Module:  evdi
Version: 1.9.1
Kernel:  4.19.0-17-amd64 (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

evdi.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.0-17-amd64/kernel/drivers/gpu/drm/evdi/
rmdir: failed to remove directory 'kernel/drivers/gpu/drm': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

DKMS: uninstall completed.

------------------------------
Deleting module version: 1.9.1
completely from the DKMS tree.
------------------------------
Done.
rm -f -rf /usr/src/evdi-1.9.1
Stopping displaylink-driver systemd service
[ Removing suspend-resume hooks ]
[ Removing udev rule ]
[ Removing Core folder ]

Uninstallation steps complete.
Please note that the evdi kernel module is still in the memory.
A reboot is required to fully complete the uninstallation process.
Removing Displaylink Xorg config file

-------------------------------------------------------------------

Performing clean-up
$ 

After reboot I used the install instead:
--------------------------- displaylink-debian -------------------------------

DisplayLink driver installer for Debian and Ubuntu based Linux distributions:

* Debian, Ubuntu, Elementary OS, Mint, Kali, Deepin and many more!
* Full list of all supported platforms: http://bit.ly/2zrwz2u
* When submitting a new issue, include Debug information

Options:

[I]nstall
[D]ebug
[R]e-install
[U]ninstall
[Q]uit

Select a key: [i/d/r/u/q]: I

-------------------------------------------------------------------

Checking dependencies

unzip is installed
linux-headers-4.19.0-17-amd64 is installed
dkms is installed
lsb-release is installed
linux-source is installed
x11-xserver-utils is installed
wget is installed
libdrm-dev is installed
libelf-dev is installed
git is installed
pciutils is installed

Platform requirements satisfied, proceeding ...

-------------------------------------------------------------------

Please read the Software License Agreement available at: 
https://www.synaptics.com/node/4036?filetype=exe
Do you accept?: [Y/n]: Y

Downloading DisplayLink Ubuntu driver:

--2021-09-16 07:21:01--  https://www.synaptics.com/sites/default/files/exe_files/2021-09/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu5.4.1-EXE.zip
Resolving www.synaptics.com (www.synaptics.com)... 52.39.229.228, 34.210.13.121
Connecting to www.synaptics.com (www.synaptics.com)|52.39.229.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14500327 (14M) [application/zip]
Saving to: ‘DisplayLink_Ubuntu_5.4.1.zip’

DisplayLink_Ubuntu_5.4.1 100%[==================================>]  13.83M   471KB/s    in 30s     

2021-09-16 07:21:31 (478 KB/s) - ‘DisplayLink_Ubuntu_5.4.1.zip’ saved [14500327/14500327]


-------------------------------------------------------------------

Preparing for install

Archive:  DisplayLink_Ubuntu_5.4.1.zip
  inflating: 5.4.1/displaylink-driver-5.4.1-55.174.run  
Creating directory displaylink-driver-5.4.1-55.174
Verifying archive integrity...  100%   All good.
Uncompressing DisplayLink Linux Driver 5.4.1-55.174  100%  
patching file 5.4.1/displaylink-driver-5.4.1/displaylink-installer.sh
Hunk #1 succeeded at 456 (offset -1 lines).

Installing driver version: 5.4.1

DisplayLink Linux Software 5.4.1-55.174 install script called: install
Distribution discovered: Debian GNU/Linux 10 (buster)

Installing

[ Installing EVDI ]
[[ Installing EVDI DKMS module ]]

Creating symlink /var/lib/dkms/evdi/1.9.1/source ->
                 /usr/src/evdi-1.9.1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.19.0-17-amd64 all INCLUDEDIR=/lib/modules/4.19.0-17-amd64/build/include KVERSION=4.19.0-17-amd64 DKMS_BUILD=1.....
cleaning build area...

DKMS: build completed.

evdi.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-17-amd64/kernel/drivers/gpu/drm/evdi/

depmod....

DKMS: install completed.
[[ Installing module configuration files ]]
[[ Installing EVDI library ]]
cc -I../module -std=gnu99 -fPIC -D_FILE_OFFSET_BITS=64    -c -o evdi_lib.o evdi_lib.c
cc evdi_lib.o -shared -Wl,-soname,libevdi.so.0 -o libevdi.so.1.9.1 -lc -lgcc 
cp libevdi.so.1.9.1 libevdi.so
[ Installing x64-ubuntu-1604/DisplayLinkManager ]
[ Installing libraries ]
[ Installing firmware packages ]
[ Installing licence file ]
[ Adding udev rule for DisplayLink DL-3xxx/4xxx/5xxx/6xxx devices ]
[ Adding upstart and powermanager sctripts ]

Please read the FAQ
http://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu

Installation complete!
Adding udlfb to blacklist
Adding udl to blacklist

-------------------------------------------------------------------

Performing post install steps

Enable and start displaylink-driver service
Created symlink /etc/systemd/system/multi-user.target.wants/displaylink-driver.service → /lib/systemd/system/displaylink-driver.service.
Setup DisplayLink xorg.conf depending on graphics card
Wrote X11 changes to: /etc/X11/xorg.conf.d/20-displaylink.conf

-------------------------------------------------------------------

Performing clean-up
Removing redundant: "DisplayLink_Ubuntu_5.4.1.zip" file
Removing redundant: "5.4.1" directory

-------------------------------------------------------------------

Install complete, please reboot to apply the changes
After reboot, make sure to consult post-install guide! http://bit.ly/2TbZleK
Reboot now? [Y/n] 

Debug output after installation complete and still not working:
--------------------------- displaylink-debian -------------------------------

DisplayLink driver installer for Debian and Ubuntu based Linux distributions:

* Debian, Ubuntu, Elementary OS, Mint, Kali, Deepin and many more!
* Full list of all supported platforms: http://bit.ly/2zrwz2u
* When submitting a new issue, include Debug information

Options:

[I]nstall
[D]ebug
[R]e-install
[U]ninstall
[Q]uit

Select a key: [i/d/r/u/q]: d

-------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] Y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] Y

--------------- Linux system info ----------------

Distro: Debian
Release: buster
Kernel: 4.19.0-17-amd64

---------------- DisplayLink info ----------------

Driver version: 1.9.1
DisplayLink service status: up and running
EVDI service version: 1.9.1

------------------ Graphics card -----------------

Vendor: i915
Subsystem: Processor
Radeon
VGA: Intel Corporation Core Processor Integrated Graphics Controller (rev 02)
Advanced Micro Devices, Inc. [AMD/ATI] Madison [Mobility Radeon HD 5650/5750 / 6530M/6550M]
VGA (3D): 
X11 version: 1.20.4-1+deb10u3
X11 configs: /etc/X11/xorg.conf.d/synaptics.conf /etc/X11/xorg.conf.d/20-displaylink.conf /etc/X11/xorg.conf.d/10-evdev.conf /etc/X11/xorg.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "Device"
    Identifier  "Intel"
    Driver      "intel"
EndSection

-------------------- Monitors --------------------

Providers: number : 1
Provider 0: id: 0x45 cap: 0xb, Source Output, Sink Output, Sink Offload crtcs: 3 outputs: 3 associated providers: 0 name:Intel

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------

Need anything else let me know.

Thanks,
Kurt

**Comment by Barabazs** [comment]
What is the content of these files:
 /etc/X11/xorg.conf.d/synaptics.conf
/etc/X11/xorg.conf.d/10-evdev.conf 
/etc/X11/xorg.conf

Maybe they are causing a conflict.
