### ISSUE TITLE
impossible to turn off or close laptop screen

### ISSUE THREAD

**Issue by GWev** [AdnanHodzic/displaylink-debian#605]
Display-link i-tec 5k dual 4k display cadual 4k docking station issue
works fine, but impossible to turn off or close laptop screen
As soon as I want to turn of the laptop screen or simply close it, the two main screens on docking station stay on but laptop works only in extreme slow motion at best. no sign in CPU usage detectable. Have the same issue on a Thinkpad and HP, newer and older models. Any solution welcome!

**Comment by CmdrBugbear** [comment]
Hi, just want to report that I'm experiencing similar symptoms.

A few nights ago I installed Debian 11 on my laptop.  Closing the laptop lid dramatically reduces the refresh rate of the attached monitors (although oddly enough, the mouse pointer responds normally).

Writing this entry on a different partition on the same laptop, will update with log files shortly

Cheers!
