### ISSUE TITLE
Freeze of Pop OS Gnome UI when adjusting display settings

### ISSUE THREAD

**Issue by bwyyoung** [AdnanHodzic/displaylink-debian#613]
After installing displaylink debian, on POP! OS 21.04,

All monitors show up as displaylink.
I have 1 laptop screen - 1920x1080
External Displaylink screens:
2560x1440
1920x1080

When I go under display settings in POP! OS and try to rearrange the positions of the monitors, and click APPLY,
the whole UI freezes for POP! OS.

Pressing CTRL ALT F1 / F2 does not work, whole system hang.

This has occurred on both official driver, and this custom driver in github.

Any idea on the cause of the problem?

**Comment by RaphaelJenni** [comment]
Same problem for me on Ubuntu.

**Comment by The-Almighty-Sasquatch** [comment]
I too have this issue, it has been long running and I have posted several issues. Is there a work around for this at all?

Thanks

**Comment by Barabazs** [comment]
Unfortunately nothing that displaylink-debian can do. It's probably settings related and requires fine-tuning.

**Comment by SamSpiri** [comment]
As workaround I manually entered desired settings into my ~/.config/monitors.xml and never touched settings in GUI
