### ISSUE TITLE
DisplayLink Ubuntu driver installation error

### ISSUE THREAD

**Issue by ristakaen** [AdnanHodzic/displaylink-debian#617]
Hi, thanks for making this utility. During installation, I encounter an error when it reaches the DisplayLink Ubuntu driver installation. It's pretty clear where the error is, and I will be modifying the script to be able to work for my particular situation.

Note the discrepancy in filename structure - the script is looking for displaylink-driver-5.4.1.[0-9]*.run whereas the file is named displaylink-driver.5.4.1-[0-9]*.run.

"""
Preparing for install

Archive:  DisplayLink_Ubuntu_5.4.1.zip
  inflating: 5.4.1/displaylink-driver-5.4.1-55.174.run  
chmod: cannot access '5.4.1/displaylink-driver-5.4.1.[0-9]*.run': No such file or directory
"""

**Comment by Barabazs** [comment]
Thank you for reporting this. The script has been updated.
