### ISSUE TITLE
Laptop crashes after closing the lid

### ISSUE THREAD

**Issue by akif-yazici** [AdnanHodzic/displaylink-debian#620]
First, I have been using this tool for a number of years and thank you all the contributors for this.
I have the displaylink dock at my office but not at home. I came into my office today after a while as I was mainly working from home. When I plugged in the dock, my external monitor did not work. I uninstalled and then installed again using the script on the terminal. Now, it kind of does work, as after a boot, when I plug in the dock, external monitor shows secondary desktop. Also, I can see two monitors side by side on ARandR. But, when I close the lid of my laptop, external monitor doesn't become the main display automatically. (I did have this behavior earlier.) Moreover, when I open the lid back on, the laptop monitor is all black. Even the cursor is nowhere to be seen. I tried to open a terminal with ctrl+alt+t and move it to the external monitor with shift+super+right and it didn't work. The laptop responded to nothing and I had to force a manual shutdown. Also, it didn't boot properly if the dock was plugged in to the USB.
The output of "sudo ./displaylink-debian.sh --debug" is below. I hope I included all necessary information. Thanks for any help you can give.

-------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

--------------- Linux system info ----------------

Distro: Ubuntu
Release: focal
Kernel: 5.11.0-34-generic

---------------- DisplayLink info ----------------

Driver version: 1.9.1
DisplayLink service status: up and running
EVDI service version: 1.9.1

------------------ Graphics card -----------------

Vendor: i915
Subsystem: 630
VGA: Intel Corporation UHD Graphics 630 (Mobile)
VGA (3D): NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)
X11 version: 1.20.11-1ubuntu1~20.04.2
X11 configs: /etc/X11/xorg.conf.d/20-displaylink.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "intel"
EndSection

Section "Device"
    Identifier "intel"
    Driver "modesetting"
    Option "AccelMethod" "None"
EndSection

Section "Screen"
    Identifier "intel"
    Device "intel"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    Option "ConstrainCursor" "off"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration" "on"
    Option "IgnoreDisplayDevices" "CRT"
EndSection

-------------------- Monitors --------------------

Providers: number : 6
Provider 0: id: 0x1b8 cap: 0x1, Source Output crtcs: 0 outputs: 0 associated providers: 5 name:NVIDIA-0
Provider 1: id: 0x2da cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0x2b8 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 3: id: 0x296 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 4: id: 0x274 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 5: id: 0x1df cap: 0x2, Sink Output crtcs: 3 outputs: 4 associated providers: 1 name:modesetting

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------

**Comment by Barabazs** [comment]
You could try to automate changing the monitor switching like in https://github.com/AdnanHodzic/displaylink-debian/blob/master/post-install-guide.md#automated-persistent-display-configuration. But that's beyond the scope of this repo.
