### ISSUE TITLE
New Platform Request- add Ubuntu Cinnamon Remix

### ISSUE THREAD

**Issue by wifechangingmoney** [AdnanHodzic/displaylink-debian#624]
Hello, 

**_Many thanks for your modified drivers for DisplayLink.  I'd like to request that Ubuntu Cinnamon Remix be added.  I run the stock OS.  Below I will list errors during install, in the log file, and upon running debug.  Thanks for your assistance!_**

**_The error I got during install is:_**
```
make -j8 KERNELRELEASE=5.11.0-34-generic all INCLUDEDIR=/lib/modules/5.11.0-34-generic/build/include KVERSION=5.11.0-34-generic DKMS_BUILD=1...(bad exit status: 2)
ERROR (dkms apport): binary package for evdi: 1.9.1 not found
Error! Bad return status for module build on kernel: 5.11.0-34-generic (x86_64)
Consult /var/lib/dkms/evdi/1.9.1/build/make.log for more information.
ERROR: Failed to install evdi to the kernel tree.
```

**_The error in the referenced log file is:_**
```
DKMS make.log for evdi-1.9.1 for kernel 5.11.0-34-generic (x86_64)
Tue Sep 21 13:39:10 MDT 2021
make KBUILD_VERBOSE=1 M=/var/lib/dkms/evdi/1.9.1/build SUBDIRS=/var/lib/dkms/evdi/1.9.1/build SRCROOT=/var/lib/dkms/evdi/1.9.1/build CONFIG_MODULE_SIG= -C /lib/modules/5.11.0-34-generic/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.11.0-34-generic'
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (                \
echo >&2;                                                       \
echo >&2 "  ERROR: Kernel configuration is invalid.";           \
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
echo >&2 ;                                                      \
/bin/false)

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

make[1]: *** [Makefile:745: include/config/auto.conf] Error 1
make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-34-generic'
```

_**The error when running debug is:**_

```
Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

--------------- Linux system info ----------------

Distro: Ubuntu
Release: hirsute
Kernel: 5.11.0-34-generic

---------------- DisplayLink info ----------------

Driver version: 1.9.1
5.2.14
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: i915
Subsystem: Graphics
VGA: Intel Corporation TigerLake GT2 [Iris Xe Graphics] (rev 01)
VGA (3D): 
X11 version: 1.20.11-1ubuntu1.1
X11 configs: /etc/X11/xorg.conf.d/00-keyboard.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No such file or directory
Contents:
 

-------------------- Monitors --------------------

Providers: number : 1
Provider 0: id: 0x46 cap: 0x9, Source Output, Sink Offload crtcs: 4 outputs: 3 associated providers: 0 name:modesetting

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------
```

**Comment by Barabazs** [comment]
How did you try to install it? Can you post the output of `sudo ./displaylink-debian.sh --install`

**Comment by wifechangingmoney** [comment]
I get a command not found error.  This also occurs for the last command on
your main instructions:

sudo apt-get install git

git clone https://github.com/AdnanHodzic/displaylink-debian.git

*cd displaylink-debian/ && sudo ./displaylink-debian.sh*

**Comment by wifechangingmoney** [comment]
*Here is the output:*


sudo ./displaylink-debian.sh --install

-------------------------------------------------------------------

Checking dependencies

unzip is installed
linux-headers-5.11.0-37-generic is installed
dkms is installed
lsb-release is installed
linux-source is installed
x11-xserver-utils is installed
wget is installed
libdrm-dev is installed
libelf-dev is installed
git is installed
pciutils is installed

Platform requirements satisfied, proceeding ...

-------------------------------------------------------------------

Please read the Software License Agreement available at:
https://www.synaptics.com/node/4036?filetype=exe
Do you accept?: [Y/n]: y

Downloading DisplayLink Ubuntu driver:

--2021-10-09 09:59:28--
https://www.synaptics.com/sites/default/files/exe_files/2021-09/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu5.4.1-EXE.zip
Resolving www.synaptics.com (www.synaptics.com)... 52.38.153.80,
34.210.13.121
Connecting to www.synaptics.com (www.synaptics.com)|52.38.153.80|:443...
connected.
HTTP request sent, awaiting response... 200 OK
Length: 14500327 (14M) [application/zip]
Saving to: ‘DisplayLink_Ubuntu_5.4.1.zip’

DisplayLink_Ubuntu_ 100%[===================>]  13.83M  3.24MB/s    in 5.0s


2021-10-09 09:59:33 (2.75 MB/s) - ‘DisplayLink_Ubuntu_5.4.1.zip’ saved
[14500327/14500327]

Removing prior: "5.4.1" directory

-------------------------------------------------------------------

Preparing for install

Archive:  DisplayLink_Ubuntu_5.4.1.zip
  inflating: 5.4.1/displaylink-driver-5.4.1-55.174.run
Creating directory displaylink-driver-5.4.1-55.174
Verifying archive integrity...  100%   All good.
Uncompressing DisplayLink Linux Driver 5.4.1-55.174  100%
patching file 5.4.1/displaylink-driver-5.4.1/displaylink-installer.sh
Hunk #1 succeeded at 456 (offset -1 lines).

Installing driver version: 5.4.1

DisplayLink Linux Software 5.4.1-55.174 install script called: install
Distribution discovered: Ubuntu 21.04

Installing

[ Installing EVDI ]
[[ Installing EVDI DKMS module ]]
Error! DKMS tree already contains: evdi-1.9.1
You cannot add the same module/version combo more than once.
EVDI DKMS module already installed.
[[ Installing module configuration files ]]
[[ Installing EVDI library ]]
cc -I../module -std=gnu99 -fPIC -D_FILE_OFFSET_BITS=64    -c -o evdi_lib.o
evdi_lib.c
cc evdi_lib.o -shared -Wl,-soname,libevdi.so.0 -o libevdi.so.1.9.1 -lc
-lgcc
cp libevdi.so.1.9.1 libevdi.so
[ Installing x64-ubuntu-1604/DisplayLinkManager ]
[ Installing libraries ]
[ Installing firmware packages ]
[ Installing licence file ]
[ Adding udev rule for DisplayLink DL-3xxx/4xxx/5xxx/6xxx devices ]
[ Adding upstart and powermanager sctripts ]

Please read the FAQ
http://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu

Installation complete!

-------------------------------------------------------------------

Performing post install steps

Enable and start displaylink-driver service
Job for displaylink-driver.service failed because the control process
exited with error code.
See "systemctl status displaylink-driver.service" and "journalctl -xe" for
details.
