### ISSUE TITLE
Ubuntu 21.10 - please support

### ISSUE THREAD

**Issue by krystoffff** [AdnanHodzic/displaylink-debian#630]
Hi,
would be pretty good if the driver would also support Ubuntu 21.10.
Of course I would then donate.
Thanks and kind regards,
Christoph

christoph.koeble@freenet.de

**Comment by electroCutie** [comment]
Update: I followed the debugging steps (for me the "delete the display link config file" was the one that worked)

It even hotplugs

I'll commit the (admittedly trivial) change and make a PR
