### ISSUE TITLE
Monitors freeze after any config change

### ISSUE THREAD

**Issue by Mr-Hyde** [AdnanHodzic/displaylink-debian#635]
Hi,
I have 2 problems, which are not critical for me, but I'd love to have them solved (also they might help others solve their setup problems).

**First things first: I have MSI PS63 8SC, POPOS 21.04 and the secondary monitor is ASUSMB16AC**

**My Providers(NVIDIA graphics settings):**
Providers: number : 6
Provider 0: id: 0x1b8 cap: 0x1, Source Output crtcs: 0 outputs: 0 associated providers: 5 name:NVIDIA-0
Provider 1: id: 0x2d5 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0x2b3 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 3: id: 0x291 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 4: id: 0x26f cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 5: id: 0x1e0 cap: 0x2, Sink Output crtcs: 4 outputs: 4 associated providers: 1 name:Intel 

First is that I had hybrid graphics setup and when I ran *xrandr --setprovideroutputsource 1 0* I got this error:
**X Error of failed request:  BadValue (integer parameter out of range for operation)**
for every out of my 6 providers listed. All I had to do to fix this was to set the graphics card to use NVIDIA dedicated graphics only.
My secondary monitor started working and I got this error no more. 
While I managed to get this working, I am still curious if there's some reason you might know about, why does the display link doesn't work with hybrid graphics setting.

Second is that I am kinda stuck with my secondary monitor on the right side but I am used to use it on the left side. But when I change any display settings in Gnome, both displays freeze and I can't do anything but hard reset laptop. Also if I disconnect the secondary monitor it freezes too. I can't even Mirror the displays. Pretty much it works unless I make any change to the configuration. Is there a workaround?
I also tried using  *xrandr --output DVI-I-2-1 --auto --left-of eDP1*
It has the same effect.

Thanks for any advice! :) 
**Debug output:**
[log.txt](https://github.com/AdnanHodzic/displaylink-debian/files/7402754/log.txt)

**Comment by jeffgirard** [comment]
Same behavior here, ubuntu 21.10 + displaylink latest version + nvidia discrete, everything is working perfectly unless I try to change screens position (gnome display manager or xrand or arand), it freezes completely my laptop. Will post logs and versions once back at my laptop  for another attempt
