### ISSUE TITLE
Get no Screens Debian 11

### ISSUE THREAD

**Issue by kutschwo** [AdnanHodzic/displaylink-debian#638]
Hello,
i do not get further providers

Hardware HP Elite Book 820 G3
WaveLink USB C Dock
installed with newest script from Git

Get only one Provider.
Debug Output
-------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

--------------- Linux system info ----------------

Distro: Debian
Release: bullseye
Kernel: 5.10.0-9-amd64

---------------- DisplayLink info ----------------

Driver version: 1.9.1
DisplayLink service status: up and running
EVDI service version: 1.9.1

------------------ Graphics card -----------------

Vendor: i915
Subsystem: GT2
VGA: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
VGA (3D): 
X11 version: 1.20.11-1
X11 configs: /etc/X11/xorg.conf.d/20-displaylink.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "Device"
    Identifier  "Intel"
    Driver      "intel"
EndSection

-------------------- Monitors --------------------

Providers: number : 1
Provider 0: id: 0x49 cap: 0xb, Source Output, Sink Output, Sink Offload crtcs: 4 outputs: 6 associated providers: 0 name:Intel

ls /var/log/displaylink/
'DELL 2709W_DELA032-T535J8ALFP4S.edid'   DisplayLinkManager.log   FirmwareTrace.log   FirmwareTrace.old.log   HS243HPB_HSD0000-1234567890123.edi

[DisplayLinkManager.log](https://github.com/AdnanHodzic/displaylink-debian/files/7404275/DisplayLinkManager.log)
[debug.zip](https://github.com/AdnanHodzic/displaylink-debian/files/7404280/debug.zip)

**Comment by Barabazs** [comment]
Please try to use this as a config
```
Section "OutputClass"
    Identifier  "DisplayLink"
    MatchDriver "evdi"
    Driver      "modesetting"
    Option      "AccelMethod" "none"
EndSection
```
