### ISSUE TITLE
"Can't open display" message when running sudo ./displaylink-debian.sh

### ISSUE THREAD

**Issue by z-nexx** [AdnanHodzic/displaylink-debian#639]
When I run `sudo ./displaylink-debian.sh` on Debian Bookworm/Sid I get the following message:
```
$ sudo ./displaylink-debian.sh 
No protocol specified
Can't open display :0
```

**Comment by janvlug** [comment]
On my fully up to date Librem 5 phone running PureOS, I get "Can't open display" both when running with `sudo -E` and running as `root`.

**Comment by janvlug** [comment]
On Wayland only systems, I always get `Can't open display` when running `xrandr --listproviders`.

But the command `xrandr --listmonitors` gives:

```
Monitors: 2
 0: +*XWAYLAND0 2560/600x1440/340+2560+0  XWAYLAND0
 1: +XWAYLAND1 2560/600x1440/340+0+0  XWAYLAND1
```

Note: when logged in via `ssh` running `xrandr --listmonitors` gives also `Can't open display`.

I think that out-commenting the line:
```
providers="$(xrandr --listproviders)"
```
(currently line 53)

from the `displaylink-debian.sh` script does not hurt and makes the script to continue on Wayland only systems.
