### ISSUE TITLE
pcilib: Cannot open /proc/bus/pci when installing

### ISSUE THREAD

**Issue by mishave** [AdnanHodzic/displaylink-debian#642]
DEVICE=RPI 3B v1.2 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux

After `git clone https://github.com/AdnanHodzic/displaylink-debian.git`

`cd displaylink-debian/ && sudo ./displaylink-debian.sh`
output:
```pcilib: Cannot open /proc/bus/pci
lspci: Cannot find any working access method.
pcilib: Cannot open /proc/bus/pci
lspci: Cannot find any working access method.
pcilib: Cannot open /proc/bus/pci
lspci: Cannot find any working access method.
pcilib: Cannot open /proc/bus/pci
lspci: Cannot find any working access method.
Can't open display 
```

not sure where to start

**Comment by Barabazs** [comment]
Raspbian is not supported.
You can try https://support.displaylink.com/knowledgebase/articles/1883065-using-arm-binaries-on-raspbian-on-raspberry-pi , but iirc it's not trivial to get a working system...
