### ISSUE TITLE
ZorinOS Pro 16 Driver Request

### ISSUE THREAD

**Issue by lavabrothers** [AdnanHodzic/displaylink-debian#643]
Here is the output of the information 'sudo ./displaylink-debian.sh --debug' as requested when providing a support request. The driver refuses to install via the script as it doesn't support Zorin

--------------- Linux system info ----------------

Distro: Zorin
Release: focal
Kernel: 5.11.0-38-generic

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: amdgpu
Subsystem: Ltd
VGA: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] (rev c1)
VGA (3D): 
X11 version: 1.20.11-1ubuntu1~20.04.2

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No such file or directory
Contents:
 

-------------------- Monitors --------------------

Providers: number : 1
Provider 0: id: 0x59 cap: 0x9, Source Output, Sink Offload crtcs: 6 outputs: 4 associated providers: 0 name:AMD Radeon RX 5700 XT @ pci:0000:0b:00.0

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------
Hello! I was wondering if it was possible to get the debian displaylink driver to work on Zorin? It works wonderfully for my Linux Mint 20 install and you do amazing work!
If that is not possible, all good. Thank you for reading and considering!

**Comment by Barabazs** [comment]
Hi @lavabrothers I've updated the script. Can you try again please?

**Comment by lavabrothers** [comment]
It installed well, same as Linux Mint. For some reason I was unable to get it working unfortunately. There is no display out of the d6000 dock
