### ISSUE TITLE
After installing displaylink Debian still nothing

### ISSUE THREAD

**Issue by MaximilianCF** [AdnanHodzic/displaylink-debian#648]
Hello,

After installing displaylink for Debian, here is my debug output

--------------- Linux system info ----------------

Distro: Debian
Release: bullseye
Kernel: 5.10.0-9-amd64

---------------- DisplayLink info ----------------

Driver version: 1.9.0+dfsg
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: i915
Subsystem: E3-1200
VGA: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
VGA (3D): 
X11 version: 1.20.11-1

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: Arquivo ou diretório inexistente
Contents:
 

-------------------- Monitors --------------------

Providers: number : 1
Provider 0: id: 0x43 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 2 outputs: 2 associated providers: 0 name:modesetting

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)
-------------------------------------------------------------------

As you can see I do not have the 20-displaylink.conf file. Never had even after installation of displaylink. Which I guess is not installed.

My xrandr --listproviders follows as:

Providers: number : 1
Provider 0: id: 0x43 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 2 outputs: 2 associated providers: 0 name:modesetting

I have one monitor on HDMI output and another VGA on the onboard graphic card. I am trying to pur another VGA monitor on displaylink.

Hope I can use displaylink in Debian. Ubuntu is not a very good choice to me...

Thanks in advance.

A

**Comment by crim-git** [comment]
Hi 
on Debian Buster ( 11 ) I solve the problem by removing 
/etc/X11/xorg.conf.d/20-displaylink.conf
just after install 

And for using only attached screen to dock ( aka not using my laptop screen ) , I add 
LIBGL_DRI3_DISABLE=true
to /etc/environment
to prevent slow display on screen for firefox and other application 

C.
