### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by pa102** [AdnanHodzic/displaylink-debian#65]
Get the following error when running in Ubuntu 16.04;

./displaylink-debian.sh: 33: ./displaylink-debian.sh: Syntax error: "(" unexpected

Thanks for any help and thanks for working to make DL less painful in Linux! :)

**Comment by AdnanHodzic** [comment]
I just verified, and install worked flawlessly for me on Ubuntu 16.04.

Please reset code changes and pull the latest sources `git reset --hard && git pull` and run `./displaylink-debian.sh` again

**Comment by pa102** [comment]
Cloned a fresh copy and still get the same issue. Could it be related to something else, like the version of bash or something similar?

**Comment by AdnanHodzic** [comment]
Definitely, which she'll are you using/version?

**Comment by pa102** [comment]
bash 4.3-14ubuntu1.1 according to dpkg

**Comment by AdnanHodzic** [comment]
What does following return:

```
ls -l /bin/sh
ls -l /bin/bash
```

**Comment by pa102** [comment]
lrwxrwxrwx 1 root root 4 Mar 31 14:37 /bin/sh -> dash
-rwxr-xr-x 1 root root 1037528 May 16 13:49 /bin/bash

**Comment by pa102** [comment]
I tried this again today now that DisplayLink have updated the drivers and it worked perfectly.

Thanks for your help.
