### ISSUE TITLE
Please update Readme.md

### ISSUE THREAD

**Issue by maniac-0s** [AdnanHodzic/displaylink-debian#653]
It doesn't work as described

    ~& sudo ./displaylink-debian.sh 
    [sudo] password for maniacos: 
    No protocol specified
    Can't open display :0.0

Of course, root can't access the display running for user.

    $ ./displaylink-debian.sh 
    
    -------------------------------------------------------------------
    
    Must be run as root (i.e: 'sudo ./displaylink-debian.sh').
    
    -------------------------------------------------------------------

I don't know what you mean in the Readme, but the described commands don't work as described.

It helps when I run

    xhost +

before that. This opens my X server for all users.

**Comment by Barabazs** [comment]
Must be something about your setup. The commands are what needs to be used in almost all of the cases.
