### ISSUE TITLE
error installing drivers in Debian 11 Bookworm

### ISSUE THREAD

**Issue by RoyArgaez** [AdnanHodzic/displaylink-debian#656]
I'm trying to install the drivers on Debian 11 Bookworm, but I'm getting a kernel error.

-------------------------------------------------------------------

Checking dependencies

unzip is installed
linux-headers-5.15.0-2-amd64 is installed
dkms is installed
lsb-release is installed
linux-source is installed
x11-xserver-utils is installed
wget is installed
libdrm-dev is installed
libelf-dev is installed
git is installed
pciutils is installed

Platform requirements satisfied, proceeding ...

-------------------------------------------------------------------

Please read the Software License Agreement available at: 
https://www.synaptics.com/node/4036?filetype=exe
Do you accept?: [Y/n]: 

Downloading DisplayLink Ubuntu driver:

--2021-12-13 10:08:26--  https://www.synaptics.com/sites/default/files/exe_files/2021-09/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu5.4.1-EXE.zip
Resolviendo www.synaptics.com (www.synaptics.com)... 52.41.97.53, 34.214.248.103
Conectando con www.synaptics.com (www.synaptics.com)[52.41.97.53]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 14500327 (14M) [application/zip]
Grabando a: «DisplayLink_Ubuntu_5.4.1.zip»

DisplayLink_Ubuntu_ 100%[===================>]  13.83M  1.16MB/s    en 14s     

2021-12-13 10:08:41 (981 KB/s) - «DisplayLink_Ubuntu_5.4.1.zip» guardado [14500327/14500327]

-------------------------------------------------------------------

Preparing for install

Archive:  DisplayLink_Ubuntu_5.4.1.zip
  inflating: 5.4.1/displaylink-driver-5.4.1-55.174.run  
Creating directory displaylink-driver-5.4.1-55.174
Verifying archive integrity...  100%   All good.
Uncompressing DisplayLink Linux Driver 5.4.1-55.174  100%  
patching file 5.4.1/displaylink-driver-5.4.1/displaylink-installer.sh
Hunk #1 succeeded at 456 (offset -1 lines).

Installing driver version: 5.4.1

DisplayLink Linux Software 5.4.1-55.174 install script called: install
Distribution discovered: Debian GNU/Linux bookworm/sid

Installing

[ Installing EVDI ]
[[ Installing EVDI DKMS module ]]
Creating symlink /var/lib/dkms/evdi/1.9.1/source -> /usr/src/evdi-1.9.1

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.15.0-2-amd64 all INCLUDEDIR=/lib/modules/5.15.0-2-amd64/build/include KVERSION=5.15.0-2-amd64 DKMS_BUILD=1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.15.0-2-amd64 (x86_64)
Consult /var/lib/dkms/evdi/1.9.1/build/make.log for more information.
ERROR: Failed to install evdi to the kernel tree
------------------------------------------------------------------

**Comment by RoyArgaez** [comment]
This is my debug 

-------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

--------------- Linux system info ----------------

Distro: Debian
Release: bookworm
Kernel: 5.15.0-2-amd64

---------------- DisplayLink info ----------------

Driver version: 1.9.1
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: i915
Subsystem: 620
VGA: Intel Corporation HD Graphics 620 (rev 02)
VGA (3D): 
X11 version: 1.20.13-2

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No existe el fichero o el directorio
Contents:
 

-------------------- Monitors --------------------

Providers: number : 2
Provider 0: id: 0x44 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 2 associated providers: 0 name:modesetting
Provider 1: id: 0xcc cap: 0x5, Source Output, Source Offload crtcs: 0 outputs: 0 associated providers: 0 name:modesetting

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------

**Comment by fpetrot** [comment]
Hello Roy,
this is an evdi issue in the original displaylink, really not a problem from displaylink-debian (Thx Adnan by the way) that performs what's necessary to install on Debian.

This is the quite dirty hack I did to correct that:
- starting from the the failed install (which did not clean up), moved to `5.4.1/displaylink-driver-5.4.1`
- then `mkdir tmp && cd tmp && tar zxvf ../evdi.tar.gz`
- now the first tricky part
apply the patch given here https://github.com/nilathedragon/evdi/commit/273fbb0a67eca5f60fd2aaab0e25076dae4d8a3a#diff-c00b60aa62f1d5ca62e486eff56f6f9a22e5659f0fcd1731e8cf83c95c409bc7L23 To be fully honest I hand edited these 3 files as it takes no time
- then `tar zxvf ../../../evdi.tar.gz`, which puts this modified evdi tarball on the root of the displaylink-debian tree
- then the second tricky part (due to the fact that the install is fully automated, applies patches and stuff)
edit `displaylink-debian.sh`, and add after line 438 (`mv displaylink-driver-${version}-[0-9]*/ $driver_dir/displaylink-driver-${version}`) the following command `cp ./evdi.tar.gz $driver_dir/displaylink-driver-${version}`, and then run install (or uninstall before install if needed).
This will in effect replace the `evdi.tar.gz` that is bundled with the original `displaylink` and let `displaylink-debian` perform what it usually does.

Hope this helps,
Frédéric

**Comment by RoyArgaez** [comment]
> Hello Roy, this is an evdi issue in the original displaylink, really not a problem from displaylink-debian (Thx Adnan by the way) that performs what's necessary to install on Debian.
> 
> This is the quite dirty hack I did to correct that:
> 
> * starting from the the failed install (which did not clean up), moved to `5.4.1/displaylink-driver-5.4.1`
> * then `mkdir tmp && cd tmp && tar zxvf ../evdi.tar.gz`
> * now the first tricky part
>   apply the patch given here [nilathedragon/evdi@273fbb0#diff-c00b60aa62f1d5ca62e486eff56f6f9a22e5659f0fcd1731e8cf83c95c409bc7L23](https://github.com/nilathedragon/evdi/commit/273fbb0a67eca5f60fd2aaab0e25076dae4d8a3a#diff-c00b60aa62f1d5ca62e486eff56f6f9a22e5659f0fcd1731e8cf83c95c409bc7L23) To be fully honest I hand edited these 3 files as it takes no time
> * then `tar zxvf ../../../evdi.tar.gz`, which puts this modified evdi tarball on the root of the displaylink-debian tree
> * then the second tricky part (due to the fact that the install is fully automated, applies patches and stuff)
>   edit `displaylink-debian.sh`, and add after line 438 (`mv displaylink-driver-${version}-[0-9]*/ $driver_dir/displaylink-driver-${version}`) the following command `cp ./evdi.tar.gz $driver_dir/displaylink-driver-${version}`, and then run install (or uninstall before install if needed).
>   This will in effect replace the `evdi.tar.gz` that is bundled with the original `displaylink` and let `displaylink-debian` perform what it usually does.
> 
> Hope this helps, Frédéric

I will try later what you tell me, thank you very much for your help Frederic. I will let you know how it went when I make the change.
