### ISSUE TITLE
Anything except mirrored displays slows system to a crawl

### ISSUE THREAD

**Issue by kaianders** [AdnanHodzic/displaylink-debian#66]
Got the external display working via Dell D3100 USB 3.0 Dock, but configuration other than a mirrored display (including turning off built in display) slows system to an absolute crawl. Is there something I'm missing in the post-installation instructions? Running Ubuntu 16.04

**Comment by pa102** [comment]
[http://askubuntu.com/a/885462](http://askubuntu.com/a/885462) did the trick for me.

**Comment by kaianders** [comment]
Works much better! Thanks. Still have problems when built in screen is turned off. Any thoughts?

**Comment by pa102** [comment]
Ah, sorry. That worked for me when the built-in screen is off too.
