### ISSUE TITLE
request support for Hamonikr OS

### ISSUE THREAD

**Issue by gememy85** [AdnanHodzic/displaylink-debian#672]
Greetings from south korea, I am using Hamonikr OS(Hanla. [hamonikr-distrowatch](https://distrowatch.com/table.php?distribution=hamonikr)), a derivative distribution of linux Mint 20.3(Una).

I was hoping you guys could add this distro to a supported one. I cloned this repo tried to install it, but showed that my distro was not in the supported list. 

Thanks

**Comment by Barabazs** [comment]
Please post the output of `sudo ./displaylink-debian.sh --debug`

**Comment by gememy85** [comment]
Sorry, I just decided not to use the displaylink device.. I'll just try to buy and use a universal device.. but thanks for what you've done..!
