### ISSUE TITLE
Add support for beta driver if present.

### ISSUE THREAD

**Issue by mcoyle1960** [AdnanHodzic/displaylink-debian#679]
As of today, January 20th, there is a 5.5 beta version of the DisplayLink driver for Ubuntu. It fixes several problems for me under Ubuntu 21.10 that are present in the 5.4.1 driver.

May I request that an option be added to your script to recognize the beta driver and give the user the option to select it over the stable (ha!) release?

Thanks.

**Comment by Barabazs** [comment]
Unfortunately it probably won't be as simple as downloading the beta and installing it, so I'm not planning on supporting a beta release.
