### ISSUE TITLE
unsupported kernel...

### ISSUE THREAD

**Issue by narrington** [AdnanHodzic/displaylink-debian#680]
I'm getting an error regarding an unsupported kernel during install. I'm running debian bullseye/bookworm (testing is pinned low but some testing packages are installed). The only trip-up I believe I have is the fact I'm running a liquorix kernel. when I switch back to 5.10 (native stable kernel) the driver seems to install, though no additional providers are listed in xrandr. I suspect the missing providers is just a matter of needing to delete /etc/X11/xorg.conf.d/20-displaylink.conf.

I'm thinking this is specific to the displaylink driver installation and not to displaylink-debian as the error includes a suggestion to download and install the beta driver.

I have not tried manually installing the requisite DKMS/headers/source packages for liquorix (5.13) so it's possible that if I install on 5.10 and then reboot to 5.13, dkms may build and install the appropriate module?

**Comment by narrington** [comment]
Found the problem. line 21 specifies no newere kernel than 5.13. So my choice is either do as I suggested and attempt to install the module under the older 5.10 kernel and then hope dkms will build against the new 5.15 kernel. OR I can install the module manually from displaylink...

Decisions, decisions...

**Comment by Barabazs** [comment]
Unfortunately it probably won't be as simple as downloading the beta and installing it, so I'm not planning on supporting a beta release.
