### ISSUE TITLE
Ubuntu 22.04 support

### ISSUE THREAD

**Issue by aghand0ur** [AdnanHodzic/displaylink-debian#681]
@AdnanHodzic 
Unsuported kernel version: 5.15
Please wait for a stable DisplayLink release or try to install the beta
No support will be given for the beta version

**Comment by Barabazs** [comment]
Kernel 5.15 is not supported by DisplayLink stable version.
I'm not planning on supporting a beta release...

**Comment by aghand0ur** [comment]
It would be nice to add a bash option to fetch beta drivers if the user is willing to take the risk

**Comment by Barabazs** [comment]
Just downloading the beta driver is not hard, but it's all the subsequent handling of the file that requires more work.

**Comment by aghand0ur** [comment]
i see

**Comment by aghand0ur** [comment]
@Barabazs @AdnanHodzic 
I assume Kernel 5.15 is now  supported by DisplayLink stable version per below link:
https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu

Any plan to merge it in your too?

**Comment by Barabazs** [comment]
Hi @aghand0ur, I'm working on it right now. It should be ready later today.

**Comment by aghand0ur** [comment]
Excellent news. Thank you @Barabazs
