### ISSUE TITLE
Add support for Kali Linux 2022.1

### ISSUE THREAD

**Issue by Aotricx** [AdnanHodzic/displaylink-debian#686]
If you do you can add me on discord and I will send you $20 on cashapp or zelle for your work.
Discord: Kunaii#8179

**Comment by Barabazs** [comment]
Please post the output of `sudo ./displaylink-debian.sh --debug`

**Comment by PwnPeter** [comment]
Hire, below the output :

```bash
---------------------------------------------------------------
─$ sudo ./displaylink-debian.sh --debug

---------------------------------------------------------------

Unsuported kernel version: 5.16
Please wait for a stable DisplayLink release or try to install the beta
No support will be given for the beta version


This tool is Open Source and feel free to extend it
GitHub repo: https://github.com/AdnanHodzic/displaylink-debian/

---------------------------------------------------------------

```

**Comment by Aotricx** [comment]
hey sorry i havent been home, i should be able to do it tonight

**Comment by Balhech** [comment]
---------------------------------------------------------------

Unsuported kernel version: 5.16
Please wait for a stable DisplayLink release or try to install the beta
No support will be given for the beta version


This tool is Open Source and feel free to extend it
GitHub repo: https://github.com/AdnanHodzic/displaylink-debian/

---------------------------------------------------------------

**Comment by Barabazs** [comment]
`displaylink-debian` has now been updated.
Please try with the latest changes.
