### ISSUE TITLE
Defective function of display link on debian bullseye

### ISSUE THREAD

**Issue by MNatiello** [AdnanHodzic/displaylink-debian#689]
Hi
I am running DisplayLink on a Dell D6000 dock in order to attach an external monitor to a Dell XPS 13 9380 laptop.
The idea of an external monitor is to turn off the laptop display and close the lid. This functionality is defective in the present 
setup. When closing the lid or otherwise turning the laptop monitor off, e.g., issuing
xrandr --output eDP-1 --off
the  mouse and keyboard present a considerable lag. Issuing a click or typing a key takes 5 seconds until effective action.
Moreover, when running on 2 monitors, sometimes the mouse freezes and the external monitor goes black. After 5-10 
seconds the mouse starts working again and soon after the external monitor recovers.

Why do I believe the problem is with displaylink? If I connect the monitor to one of the free thunderbolt3 ports with another cable, 
completely bypassing the dock, and displaylink nothing of this happens. I can turn off the laptop screen and/or close the lid without experiencing any lag on keyboard or mouse, nor experiencing any "frozen mouse".

This problem started a few weeks ago when I upgraded Debian to bullseye and downloaded the newest version of 
displaylink-debian.
There is another issue, started by "ghost" about the same problem, with less information. I do not know how to close that
issue. Please, consider only this issue and disregard the other one.
Thanks
M. Natiello

--------------- Linux system info ----------------

Distro: Debian
Release: bullseye
Kernel: 5.10.0-11-amd64

---------------- DisplayLink info ----------------

Driver version: 1.9.0+dfsg
1.9.1
5.1.26
DisplayLink service status: up and running
EVDI service version: 1.9.1

------------------ Graphics card -----------------
Vendor: i915
Subsystem: 620
VGA: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620]
VGA (3D): 
X11 version: 1.20.11-1+deb11u1
X11 configs: /etc/X11/xrdp/xorg.conf /etc/X11/xorg.conf.d/20-displaylink.conf /etc/X11/xorg.conf.d/40-libinput.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "OutputClass"
    Identifier  "DisplayLink"
    MatchDriver "evdi"
    Driver      "modesetting"
    Option      "AccelMethod" "none"
EndSection

-------------------- Monitors --------------------

Providers: number : 5
Provider 0: id: 0x45 cap: 0xf, Source Output, Sink Output, Source Offload, Sink 
Offload crtcs: 3 outputs: 3 associated providers: 4 name:modesetting
Provider 1: id: 0x16e cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0x14c cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 3: id: 0x12a cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 4: id: 0x108 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting

-------------------------------------------------------------------

**Comment by Barabazs** [comment]
Those are known issues, but unfortunately without a proper fix.
I suggest reporting this on the DisplayLink forum or in the [evdi repo](https://github.com/DisplayLink/evdi)
