### ISSUE TITLE
Add support for LMDE 5 “Elsie”

### ISSUE THREAD

**Issue by ErnstAmat** [AdnanHodzic/displaylink-debian#690]
Please add support for LMDE 5 “Elsie”

--------------- Linux system info ----------------

Distro: Linuxmint
Release: elsie
Kernel: 5.10.0-11-amd64

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: vmwgfx
Subsystem: Adapter
VGA: VMware SVGA II Adapter
VGA (3D): 
X11 version: 1.20.11-1+deb11u1

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No such file or directory
Contents:
 

-------------------- Monitors --------------------

Providers: number : 0

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------

**Comment by Barabazs** [comment]
`displaylink-debian` has now been updated.
Please try with the latest changes.
