### ISSUE TITLE
Installation problem Kali Linux on Raspberry

### ISSUE THREAD

**Issue by tomcdev63** [AdnanHodzic/displaylink-debian#714]
Hi, I'm trying to install an AOC E1659FWU monitor that only connects to USB3 on my raspberry. But like davidmans7 I have a problem with the installation...

![Screenshot_2022-05-04_07_40_24](https://user-images.githubusercontent.com/72632400/166640659-93227c8c-400f-4219-be76-08218d08aa69.png)

apt search linux-source
apt show linux-source

![Screenshot_2022-05-04_07_42_25](https://user-images.githubusercontent.com/72632400/166640586-9bebf08b-c0f4-4a91-95e9-9873eb2eab91.png)

**Comment by Barabazs** [comment]
Is there a displaylink chip in your raspberry pi?

**Comment by tomcdev63** [comment]
I don't know, it's an original raspberry pi 4b, I didn't modify anything

**Comment by Barabazs** [comment]
Do you intend to connect your display directly to the Raspberry Pi (with usb)?
Then you will need to know if there is a DisplayLink chip in the RPI. (I don't think there is one) 

If there is no chip, then you will need a DisplayLink adapter to connect the display to the RPI.

**Comment by tomcdev63** [comment]
It has already worked! Thanks to these drivers (https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu) I got an image. But when I rebooted my KaliLinux everything crashed.
I had to reinstall Kali... Apparently these drivers are designed for Ubuntu and not KaliLinux

**Comment by tomcdev63** [comment]
I think it's the same problem as davidmans7... not a material problem
