### ISSUE TITLE
usb usb4-port2: cannot disable (err = -32)

### ISSUE THREAD

**Issue by Denizar** [AdnanHodzic/displaylink-debian#73]
Hi Adnan,
 
After running your installer several times on Ubuntu 16.04 I am still unable to activate my monitor.
 
My laptop has an Nvidia graphics card which as far as I've read online may potentially be causing extra issues.
 

The error I am getting on demsg upon plugging in the usb is as below:

> [    4.459016] systemd[1]: systemd 229 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN)
> [    4.459129] systemd[1]: Detected architecture x86-64.
> [    4.459312] systemd[1]: Set hostname to <deniz-dev>.
> [    4.559213] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
> [    4.559328] systemd[1]: Created slice System Slice.
> [    4.559358] systemd[1]: Listening on fsck to fsckd communication Socket.
> [    4.559460] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
> [    4.559501] systemd[1]: Listening on Journal Socket.
> [    4.574963] systemd[1]: Mounting POSIX Message Queue File System...
> [    4.575361] systemd[1]: Starting Uncomplicated firewall...
> [    4.575762] systemd[1]: Started Read required files in advance.
> [    4.576407] systemd[1]: Mounting Debug File System...
> [    4.576965] systemd[1]: Starting Create list of required static device nodes for the current kernel...
> [    4.577528] systemd[1]: Starting Set console keymap...
> [    4.581184] systemd[1]: Starting Load Kernel Modules...
> [    4.581251] systemd[1]: Listening on udev Control Socket.
> [    4.581319] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
> [    4.581351] systemd[1]: Listening on udev Kernel Socket.
> [    4.581382] systemd[1]: Listening on Journal Socket (/dev/log).
> [    4.581806] systemd[1]: Started Braille Device Support.
> [    4.581920] systemd[1]: Listening on Syslog Socket.
> [    4.581962] systemd[1]: Reached target User and Group Name Lookups.
> [    4.582061] systemd[1]: Listening on Journal Audit Socket.
> [    4.582736] systemd[1]: Starting Journal Service...
> [    4.582792] systemd[1]: Reached target Remote File Systems (Pre).
> [    4.582821] systemd[1]: Reached target Remote File Systems.
> [    4.583387] systemd[1]: Mounting Huge Pages File System...
> [    4.585599] systemd[1]: Reached target Encrypted Volumes.
> [    4.585707] systemd[1]: Created slice User and Session Slice.
> [    4.585718] systemd[1]: Reached target Slices.
> [    4.587128] systemd[1]: Started Create list of required static device nodes for the current kernel.
> [    4.591380] systemd[1]: Started Uncomplicated firewall.
> [    4.604990] systemd[1]: Mounted POSIX Message Queue File System.
> [    4.605071] systemd[1]: Mounted Huge Pages File System.
> [    4.605121] systemd[1]: Mounted Debug File System.
> [    4.611610] lp: driver loaded but no devices found
> [    4.616224] ppdev: user-space parallel port driver
> [    4.623462] scsi 4:0:0:0: Direct-Access     Multiple Card  Reader     1.00 PQ: 0 ANSI: 0
> [    4.623947] sd 4:0:0:0: Attached scsi generic sg2 type 0
> [    4.631273] systemd[1]: Starting Create Static Device Nodes in /dev...
> [    4.631827] systemd[1]: Started Load Kernel Modules.
> [    4.632782] systemd[1]: Mounting FUSE Control File System...
> [    4.633270] systemd[1]: Starting Apply Kernel Variables...
> [    4.638026] systemd[1]: Mounted FUSE Control File System.
> [    4.638455] systemd[1]: Started Apply Kernel Variables.
> [    4.646316] systemd[1]: Started Create Static Device Nodes in /dev.
> [    4.648884] systemd[1]: Started Journal Service.
> [    4.706385] EXT4-fs (sda1): re-mounted. Opts: errors=remount-ro
> [    4.778426] systemd-journald[229]: Received request to flush runtime journal from PID 1
> [    4.838660] wmi: Mapper loaded
> [    4.909006] ACPI Warning: SystemIO range 0x0000000000000428-0x000000000000042F conflicts with OpRegion 0x0000000000000400-0x000000000000044F (\GPIS) (20150930/utaddress-254)
> [    4.909014] ACPI Warning: SystemIO range 0x0000000000000428-0x000000000000042F conflicts with OpRegion 0x0000000000000400-0x000000000000047F (\PMIO) (20150930/utaddress-254)
> [    4.909018] ACPI: If an ACPI driver is available for this device, you should use it instead of the native driver
> [    4.909022] ACPI Warning: SystemIO range 0x0000000000000540-0x000000000000054F conflicts with OpRegion 0x0000000000000500-0x000000000000057F (\GPIO) (20150930/utaddress-254)
> [    4.909025] ACPI Warning: SystemIO range 0x0000000000000540-0x000000000000054F conflicts with OpRegion 0x0000000000000500-0x0000000000000563 (\GP01) (20150930/utaddress-254)
> [    4.909029] ACPI: If an ACPI driver is available for this device, you should use it instead of the native driver
> [    4.909031] ACPI Warning: SystemIO range 0x0000000000000530-0x000000000000053F conflicts with OpRegion 0x0000000000000500-0x000000000000057F (\GPIO) (20150930/utaddress-254)
> [    4.909034] ACPI Warning: SystemIO range 0x0000000000000530-0x000000000000053F conflicts with OpRegion 0x0000000000000500-0x0000000000000563 (\GP01) (20150930/utaddress-254)
> [    4.909037] ACPI: If an ACPI driver is available for this device, you should use it instead of the native driver
> [    4.909038] ACPI Warning: SystemIO range 0x0000000000000500-0x000000000000052F conflicts with OpRegion 0x0000000000000500-0x000000000000057F (\GPIO) (20150930/utaddress-254)
> [    4.909041] ACPI Warning: SystemIO range 0x0000000000000500-0x000000000000052F conflicts with OpRegion 0x0000000000000500-0x0000000000000563 (\GP01) (20150930/utaddress-254)
> [    4.909045] ACPI: If an ACPI driver is available for this device, you should use it instead of the native driver
> [    4.909046] lpc_ich: Resource conflict(s) found affecting gpio_ich
> [    4.919809] shpchp: Standard Hot Plug PCI Controller Driver version: 0.4
> [    4.926319] audit: type=1400 audit(1496225522.855:2): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/lightdm/lightdm-guest-session" pid=457 comm="apparmor_parser"
> [    4.926329] audit: type=1400 audit(1496225522.855:3): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/lightdm/lightdm-guest-session//chromium" pid=457 comm="apparmor_parser"
> [    4.928562] audit: type=1400 audit(1496225522.859:4): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/sbin/dhclient" pid=458 comm="apparmor_parser"
> [    4.928574] audit: type=1400 audit(1496225522.859:5): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=458 comm="apparmor_parser"
> [    4.928582] audit: type=1400 audit(1496225522.859:6): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-helper" pid=458 comm="apparmor_parser"
> [    4.928589] audit: type=1400 audit(1496225522.859:7): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/connman/scripts/dhclient-script" pid=458 comm="apparmor_parser"
> [    4.930441] audit: type=1400 audit(1496225522.859:8): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/bin/ubuntu-core-launcher" pid=462 comm="apparmor_parser"
> [    4.931048] audit: type=1400 audit(1496225522.863:9): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/sbin/cups-browsed" pid=471 comm="apparmor_parser"
> [    4.934291] audit: type=1400 audit(1496225522.863:10): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/sbin/ippusbxd" pid=473 comm="apparmor_parser"
> [    4.982797] random: nonblocking pool is initialized
> [    4.989683] Bluetooth: Core ver 2.21
> [    4.989697] NET: Registered protocol family 31
> [    4.989699] Bluetooth: HCI device and connection manager initialized
> [    4.989703] Bluetooth: HCI socket layer initialized
> [    4.989706] Bluetooth: L2CAP socket layer initialized
> [    4.989713] Bluetooth: SCO socket layer initialized
> [    5.005871] sd 4:0:0:0: [sdc] Attached SCSI removable disk
> [    5.010543] media: Linux media interface: v0.10
> [    5.011011] usbcore: registered new interface driver btusb
> [    5.031734] Linux video capture interface: v2.00
> [    5.061585] uvcvideo: Found UVC 1.00 device ASUS USB2.0 Webcam (1bcf:2883)
> [    5.079088] input: ASUS USB2.0 Webcam as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.0/input/input16
> [    5.079146] usbcore: registered new interface driver uvcvideo
> [    5.079147] USB Video Class driver (1.1.1)
> [    5.167400] AVX version of gcm_enc/dec engaged.
> [    5.167403] AES CTR mode by8 optimization enabled
> [    5.172148] asus_wmi: ASUS WMI generic driver loaded
> [    5.173472] asus_wmi: Initialization: 0x1
> [    5.173507] asus_wmi: BIOS WMI version: 7.6
> [    5.173557] asus_wmi: SFUN value: 0xa0877
> [    5.174048] input: Asus WMI hotkeys as /devices/platform/asus-nb-wmi/input/input17
> [    5.202891] asus_wmi: Number of fans: 1
> [    5.257048] snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC663: line_outs=2 (0x14/0x16/0x0/0x0/0x0) type:speaker
> [    5.257052] snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
> [    5.257053] snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
> [    5.257055] snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
> [    5.257056] snd_hda_codec_realtek hdaudioC0D0:    dig-out=0x1e/0x0
> [    5.257057] snd_hda_codec_realtek hdaudioC0D0:    inputs:
> [    5.257059] snd_hda_codec_realtek hdaudioC0D0:      Internal Mic=0x19
> [    5.257061] snd_hda_codec_realtek hdaudioC0D0:      Mic=0x18
> [    5.266088] input: HDA Intel PCH Mic as /devices/pci0000:00/0000:00:1b.0/sound/card0/input18
> [    5.266172] input: HDA Intel PCH Headphone as /devices/pci0000:00/0000:00:1b.0/sound/card0/input19
> [    5.390021] ath: phy0: Set BT/WLAN RX diversity capability
> [    5.395335] intel_rapl: Found RAPL domain package
> [    5.395339] intel_rapl: Found RAPL domain core
> [    5.395341] intel_rapl: Found RAPL domain uncore
> [    5.440273] ath: phy0: ASPM enabled: 0x42
> [    5.440277] ath: EEPROM regdomain: 0x60
> [    5.440278] ath: EEPROM indicates we should expect a direct regpair map
> [    5.440279] ath: Country alpha2 being used: 00
> [    5.440280] ath: Regpair used: 0x60
> [    5.444611] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
> [    5.444874] ieee80211 phy0: Atheros AR9285 Rev:2 mem=0xffffc900010e0000, irq=17
> [    5.474374] ath9k 0000:03:00.0 wlp3s0: renamed from wlan0
> [    5.898631] cfg80211: World regulatory domain updated:
> [    5.898635] cfg80211:  DFS Master region: unset
> [    5.898636] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
> [    5.898638] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
> [    5.898639] cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
> [    5.898641] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm), (N/A)
> [    5.898642] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (N/A)
> [    5.898644] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (0 s)
> [    5.898645] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2000 mBm), (0 s)
> [    5.898646] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm), (N/A)
> [    5.898648] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm), (N/A)
> [    5.982046] Adding 3905532k swap on /dev/sda5.  Priority:-1 extents:1 across:3905532k SSFS
> [    6.031868] nvidia-uvm: Loaded the UVM driver in 8 mode, major device number 243
> [    6.061396] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    6.061463] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    6.061553] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    6.061593] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    6.061631] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    6.061723] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    6.061760] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    6.119360] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    6.464715] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    6.524133] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
> [    6.524137] Bluetooth: BNEP filters: protocol multicast
> [    6.524142] Bluetooth: BNEP socket layer initialized
> [    6.577756] bbswitch: version 0.8
> [    6.577764] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
> [    6.577771] bbswitch: Found discrete VGA device 0000:01:00.0: \_SB_.PCI0.PEG0.GFX0
> [    6.577782] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    6.577899] bbswitch: detected an Optimus _DSM function
> [    6.577911] bbswitch: Succesfully loaded. Discrete card 0000:01:00.0 is on
> [    6.773134] evdi: [I] Initialising logging on level 5
> [    6.920722] audit_printk_skb: 39 callbacks suppressed
> [    6.920726] audit: type=1400 audit(1496225524.851:24): apparmor="DENIED" operation="open" profile="/usr/sbin/mysqld" name="/proc/1001/status" pid=1001 comm="mysqld" requested_mask="r" denied_mask="r" fsuid=121 ouid=121
> [    6.920764] audit: type=1400 audit(1496225524.851:25): apparmor="DENIED" operation="open" profile="/usr/sbin/mysqld" name="/sys/devices/system/node/" pid=1001 comm="mysqld" requested_mask="r" denied_mask="r" fsuid=121 ouid=0
> [    6.920814] audit: type=1400 audit(1496225524.851:26): apparmor="DENIED" operation="open" profile="/usr/sbin/mysqld" name="/proc/1001/status" pid=1001 comm="mysqld" requested_mask="r" denied_mask="r" fsuid=121 ouid=121
> [    6.938485] usb 4-2: usbfs: process 1030 (DeviceManager_0) did not claim interface 1 before use
> [    7.061905] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    7.061976] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    7.062068] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    7.062111] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    7.062152] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    7.062249] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    7.062291] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    7.062765] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    7.113022] IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is not ready
> [    7.128397] xhci_hcd 0000:04:00.0: WARN Event TRB for slot 1 ep 0 with no TDs queued?
> [    7.129406] IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is not ready
> [    7.139584] IPv6: ADDRCONF(NETDEV_UP): enp5s0: link is not ready
> [    7.156256] IPv6: ADDRCONF(NETDEV_UP): enp5s0: link is not ready
> [    7.193563] nvidia-modeset: Allocated GPU:0 (GPU-f3bc8308-8751-3c85-21ad-12699d09194e) @ PCI:0000:01:00.0
> [    7.194147] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    7.194279] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    7.194360] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    7.194436] ACPI Warning: \_SB_.PCI0.PEG0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
> [    7.253839] IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is not ready
> [    7.914449] usb 4-2: usbfs: process 1030 (DeviceManager_0) did not claim interface 1 before use
> [    8.458614] Bluetooth: RFCOMM TTY layer initialized
> [    8.458623] Bluetooth: RFCOMM socket layer initialized
> [    8.458630] Bluetooth: RFCOMM ver 1.11
> [    8.918767] usb 4-2: usbfs: process 1030 (DeviceManager_0) did not claim interface 1 before use
> [    9.923635] usb 4-2: usbfs: process 1030 (DeviceManager_0) did not claim interface 1 before use
> [   10.927647] usb 4-2: usbfs: process 1030 (DeviceManager_0) did not claim interface 1 before use
> [   11.630313] wlp3s0: authenticate with c4:6e:1f:c6:5a:c2
> [   11.644167] wlp3s0: send auth to c4:6e:1f:c6:5a:c2 (try 1/3)
> [   11.645880] wlp3s0: authenticated
> [   11.646457] wlp3s0: associate with c4:6e:1f:c6:5a:c2 (try 1/3)
> [   11.652773] wlp3s0: RX AssocResp from c4:6e:1f:c6:5a:c2 (capab=0x1411 status=0 aid=2)
> [   11.652896] wlp3s0: associated
> [   11.652937] IPv6: ADDRCONF(NETDEV_CHANGE): wlp3s0: link becomes ready
> [   58.863171] traps: pool[2710] trap int3 ip:7f0239de6a5b sp:7f02187fa6f0 error:0
> [   76.074058] xhci_hcd 0000:04:00.0: Cannot set link state.
> [   76.074065] usb usb4-port2: cannot disable (err = -32)
> [   76.074068] usb 4-2: USB disconnect, device number 2
> [   79.413015] usb 4-2: new SuperSpeed USB device number 3 using xhci_hcd
> [   79.427019] usb 4-2: New USB device found, idVendor=17e9, idProduct=ff0b
> [   79.427030] usb 4-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [   79.427035] usb 4-2: Product: ASUSTEK MB169B+
> [   79.427039] usb 4-2: Manufacturer: DisplayLink
> [   79.427043] usb 4-2: SerialNumber: h3lmtf090415
> [   80.537981] usb 4-2: usbfs: process 2827 (DeviceManager_0) did not claim interface 1 before use
> [   80.727988] xhci_hcd 0000:04:00.0: WARN Event TRB for slot 1 ep 0 with no TDs queued?
> [   81.533437] usb 4-2: usbfs: process 2827 (DeviceManager_0) did not claim interface 1 before use
> [   82.540531] usb 4-2: usbfs: process 2827 (DeviceManager_0) did not claim interface 1 before use
> [   83.547637] usb 4-2: usbfs: process 2827 (DeviceManager_0) did not claim interface 1 before use
> [   84.554408] usb 4-2: usbfs: process 2827 (DeviceManager_0) did not claim interface 1 before use
> [  142.256023] xhci_hcd 0000:04:00.0: Cannot set link state.
> [  142.256046] usb usb4-port2: cannot disable (err = -32)
> [  142.256058] usb 4-2: USB disconnect, device number 3
> [  145.187213] usb 4-2: new SuperSpeed USB device number 4 using xhci_hcd
> [  145.200746] usb 4-2: New USB device found, idVendor=17e9, idProduct=ff0b
> [  145.200766] usb 4-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [  145.200771] usb 4-2: Product: ASUSTEK MB169B+
> [  145.200775] usb 4-2: Manufacturer: DisplayLink
> [  145.200779] usb 4-2: SerialNumber: h3lmtf090415
> [  179.049876] usb 4-2: usbfs: process 3044 (DeviceManager_0) did not claim interface 1 before use
> [  179.239905] xhci_hcd 0000:04:00.0: WARN Event TRB for slot 1 ep 0 with no TDs queued?
> [  180.044446] usb 4-2: usbfs: process 3044 (DeviceManager_0) did not claim interface 1 before use
> [  181.052077] usb 4-2: usbfs: process 3044 (DeviceManager_0) did not claim interface 1 before use
> [  182.058159] usb 4-2: usbfs: process 3044 (DeviceManager_0) did not claim interface 1 before use
> [  183.064359] usb 4-2: usbfs: process 3044 (DeviceManager_0) did not claim interface 1 before use

I highlighted usb usb4-port2: cannot disable (err = -32) as the title of this issue since that was highlighted red on the terminal but that may be misleading.
 
xrandr providers:

> Providers: number : 3
> Provider 0: id: 0x2ce cap: 0x1, Source Output crtcs: 2 outputs: 1 associated providers: 1 name:NVIDIA-0
> Provider 1: id: 0x43 cap: 0x2, Sink Output crtcs: 2 outputs: 2 associated providers: 1 name:modesetting
> Provider 2: id: 0x43 cap: 0x2, Sink Output crtcs: 2 outputs: 2 associated providers: 1 name:modesetting

usbview: 
![image](https://cloud.githubusercontent.com/assets/1430946/26627783/49204960-4604-11e7-978d-f7e924332148.png)

I'd be happy to hear your comments if any. Thanks!

**Comment by AdnanHodzic** [comment]
In couple of latest commits, I've added feature which will disable pageflip for modesetting which could resolve your problem.

Could you please run re-install with latest changes and report if this same problem exists?

**Comment by AdnanHodzic** [comment]
In latest commit, I've added code which will now allow "displaylink-debian" to automatically configure your Xorg config based on your graphics card. 

This feature may still be bit rough around the edges and might need some improvement. So if you have still have problems after pulling latest changes and running "re-install", please re-open this story and add output of following commands:

`cat /etc/X11/xorg.conf.d/20-displaylink.conf`
`lspci | grep -i vga`
`lspci -nnk | grep -i vga -A3 | grep 'in use'|cut -d":" -f2|sed 's/ //g'`
`lspci -nnk | grep -i vga -A3|grep Subsystem|cut -d" " -f5`
