### ISSUE TITLE
xrandr isn't setting provider output source inside a VM

### ISSUE THREAD

**Issue by gnutechie** [AdnanHodzic/displaylink-debian#740]
I am trying to use a displaylink device in a KVM QEMU guest VM with Debian 11 (Cinnamon with software rendering).
Driver installs ok but when I go for: xrandr --setprovideroutputsource 1 0 it gives me the following error:

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  35 (RRSetProviderOutputSource)
  Value in failed request:  0x47
  Serial number of failed request:  19
  Current serial number in output stream:  20

Here is the rest of the debugging info.
-------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

--------------- Linux system info ----------------

Distro: Debian
Release: bullseye
Kernel: 5.18.0-0.bpo.1-amd64

---------------- DisplayLink info ----------------

Driver version: 1.12.0
DisplayLink service status: up and running
EVDI service version: 1.12.0

------------------ Graphics card -----------------

Vendor: qxl
Subsystem: QEMU
VGA: Red Hat, Inc. QXL paravirtual graphic card (rev 05)
VGA (3D): 
X11 version: 1.20.11-1+deb11u2
X11 configs: /etc/X11/xorg.conf.d/20-displaylink.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "OutputClass"
    Identifier  "DisplayLink"
    MatchDriver "evdi"
    Driver      "modesetting"
    Option      "AccelMethod" "none"
[dmesg-log.txt](https://github.com/AdnanHodzic/displaylink-debian/files/9349343/dmesg-log.txt)
EndSection

-------------------- Monitors --------------------

Providers: number : 5
Provider 0: id: 0x47 cap: 0x0 crtcs: 4 outputs: 4 associated providers: 0 name:qxl
Provider 1: id: 0xf4 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 2: id: 0xd2 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 3: id: 0xb0 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 4: id: 0x8e cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting

-------------------------------------------------------------------

 I'm also attaching the VM's dmesg logs just in case there's something there that i missed.
 
[dmesg-log.txt](https://github.com/AdnanHodzic/displaylink-debian/files/9349355/dmesg-log.txt)

Hope someone else has encountered this. Thanks in advance for your time and effort

**Comment by Barabazs** [comment]
Sorry, this is out of scope for this repo.
