### ISSUE TITLE
I'got this problex: "linux-source" not installed. Can you help me?

### ISSUE THREAD

**Issue by isabellafloriani** [AdnanHodzic/displaylink-debian#741]
keep@thinkeep:~/Downloads/displaylink-debian-master$ sudo ./displaylink-debian.sh

--------------------------- displaylink-debian -------------------------------

DisplayLink driver installer for Debian and Ubuntu based Linux distributions:

* Debian, Ubuntu, Elementary OS, Mint, Kali, Deepin and many more!
* Full list of all supported platforms: http://bit.ly/2zrwz2u
* When submitting a new issue, include Debug information

Options:

[I]nstall
[D]ebug
[R]e-install
[U]ninstall
[Q]uit

Select a key: [i/d/r/u/q]: i

-------------------------------------------------------------------

Checking dependencies

unzip is installed
linux-headers-4.19.0-5-amd64 is installed
dkms is installed
lsb-release is installed
dpkg-query: o pacote 'linux-source' não está instalado e não está disponível informação
Utilize dpkg --info (= dpkg-deb --info) para examinar ficheiros de arquivo.
linux-source not found! Install? [Y/n] ^C
keep@thinkeep:~/Downloads/displaylink-debian-master$

**Comment by Barabazs** [comment]
You need to accept the install with "Y"
