### ISSUE TITLE
only a message is displayed that says "check signal cable"

### ISSUE THREAD

**Issue by MrPessimist** [AdnanHodzic/displaylink-debian#744]
Hello, After installing the driver and following the post installation section, I still cannot see any image on the 3rd screen.

Device: USB32HD2.

The output of the ./displaylink-debian.sh --debug command:
-------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

--------------- Linux system info ----------------

Distro: Linuxmint
Release: elsie
Kernel: 5.10.0-17-amd64

---------------- DisplayLink info ----------------

Driver version: 1.12.0
1.9.0+dfsg
DisplayLink service status: up and running
EVDI service version: 1.12.0

------------------ Graphics card -----------------

Vendor: i915
Subsystem: Gen
VGA: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
VGA (3D): 
X11 version: 1.20.11-1+deb11u2
X11 configs: /etc/X11/xorg.conf.d/20-displaylink.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "OutputClass"
    Identifier  "DisplayLink"
    MatchDriver "evdi"
    Driver      "modesetting"
    Option      "AccelMethod" "none"
EndSection

-------------------- Monitors --------------------

Providers: number : 5
Provider 0: id: 0x46 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 4 associated providers: 4 name:modesetting
Provider 1: id: 0x140 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0x11e cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 3: id: 0xfc cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 4: id: 0xda cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------

I tried the device on a computer with OS windows and it works without problems, which makes me rule out that the device is bad.

The 3rd screen is with VGA input. I have tried with two cables to rule out problems with the cable as well.

when I connect the 3rd screen I get the following output in the log:

Aug 29 12:39:32  kernel: [ 2983.931837] usb 3-2: new high-speed USB device number 9 using xhci_hcd
Aug 29 12:39:32  kernel: [ 2984.080730] usb 3-2: New USB device found, idVendor=0711, idProduct=5601, bcdDevice=10.10
Aug 29 12:39:32  kernel: [ 2984.080740] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Aug 29 12:39:32  kernel: [ 2984.080744] usb 3-2: Product: T6 USB Station
Aug 29 12:39:32  kernel: [ 2984.080747] usb 3-2: Manufacturer: MCT Corp.
Aug 29 12:39:32  mtp-probe: checking bus 3, device 9: "/sys/devices/pci0000:00/0000:00:14.0/usb3/3-2"
Aug 29 12:39:32  mtp-probe: bus: 3, device: 9 was not an MTP device
Aug 29 12:39:32  mtp-probe: checking bus 3, device 9: "/sys/devices/pci0000:00/0000:00:14.0/usb3/3-2"
Aug 29 12:39:32  mtp-probe: bus: 3, device: 9 was not an MTP device

Could it be that the device in question is not compatible with the drivers? I searched for information and did not find anything that mentioned any restrictions on it.

Thanks in advance.

**Comment by Barabazs** [comment]
> Could it be that the device in question is not compatible with the drivers? I searched for information and did not find anything that mentioned any restrictions on it.

This doesn't seem like a DisplayLink device. You should check the specifications from the vendor.

**Comment by MrPessimist** [comment]
I read the manufacturer's specification the Chipset ID is Trigger T6-688SL Silicon Image-Sil9136-3. 

Thanks anyway.      ;(  ;(
