### ISSUE TITLE
Ubuntu 16.04.2 suspension issue

### ISSUE THREAD

**Issue by i2000s** [AdnanHodzic/displaylink-debian#75]
I tried to suspend my Ubuntu 16.04.2 laptop by closing the lid, but the curser started jittering around rapidly once the lid was closed. It also seemed that the left button of the mouse was pressed at the same time (I did nothing on that). All of these prevented my computer from sleeping as usual. The latest DisplayLink driver for Ubuntu has been installed using the script. My computer model is Lenovo Thinkpad P50. External monitor: ViewSonic VG2230wn.

I have a Microsoft Wireless mouse plugged into the displaylink ports. The same issue occurs if I turn off the mouse. It has no problem to suspend my computer if the Displaylink is not in use. 
I have used xrandr to set up the external monitor; otherwise, the external monitor doesn't show up.

Any idea?
Thanks!

**Comment by AdnanHodzic** [comment]
In couple of latest commits, I've added feature which will disable pageflip for modesetting which could resolve your problem.

Could you please run re-install with latest changes and report if this same problem exists?

**Comment by AdnanHodzic** [comment]
@i2000s no worries changes have been tested and merged with master. 

Good luck with your new display :)
