### ISSUE TITLE
Feature Request: Multiseat settings file setup.

### ISSUE THREAD

**Issue by gnutechie** [AdnanHodzic/displaylink-debian#752]
Hey guys,

Your script works pretty well (except that I need to run xrandr --setprovideroutputsource 4 0 to get it to work properly).

Would it be possible to add setup file creation for Multiseat configurations both for lightdm and Xserver configurations so we can get multi-seat working with the displaylink devices?

Thank you for your time and your consideration

**Comment by Barabazs** [comment]
Sorry, this is out of scope for this repo.
