### ISSUE TITLE
Doesn't work under Debian GNU Linux Kernel linux-image-5.19.0-2-amd64

### ISSUE THREAD

**Issue by marcelolaia** [AdnanHodzic/displaylink-debian#754]
Doesn't work under Debian GNU Linux Kernel linux-image-5.19.0-2-amd64 version 5.19.11-1 amd64.

Under linux-image-5.19.0-1-amd64 version 5.19.6-1 it works fine.

**Comment by tddpirate** [comment]
Check pull request https://github.com/AdnanHodzic/displaylink-debian/pull/758.

**Comment by Barabazs** [comment]
Fixed in #775
