### ISSUE TITLE
Script doesn't return displaylink version in wget

### ISSUE THREAD

**Issue by sh-one** [AdnanHodzic/displaylink-debian#76]
Hi - Problem in line 14 of the script (version='wget....)
This line returns nothing now from the DisplayLink website
I've used your script recently and it worked until about a week ago.
If I remove the perl part of this line I get output of:
<a href="/downloads/file?id=744" title="Download File" onclick="">DisplayLink USB Graphics Software for Ubuntu</a>
No version number listed just the id=744.
I guess the perl regex needs to change. I'm no great perl programmer otherwise I might have a go at this myself.

**Comment by saljut7** [comment]
thx @adangel - you fix works fine for me.
