### ISSUE TITLE
Lag on rendering of all screens while displaylink is plugged in - Ubuntu 22.04 

### ISSUE THREAD

**Issue by sashrafoxit** [AdnanHodzic/displaylink-debian#760]
Hello,

I have a fresh installation of Ubuntu 22.04 on a new laptop with a single HDMI port and no USB-C support to add external monitors. I bought [this display link device](https://www.amazon.de/gp/product/B01AL6IBF8/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1) for it.

Without any drivers installation and with drivers installation there is extreme lag on the whole computer rendering when this screen is connected.

This is the output of --debug command. I noticed that driver versions are 1.12 not 5.6, I uninstalled, rebooted and reinstalled multiple times, it's always 1.12.

```
--------------- Linux system info ----------------

Distro: Ubuntu
Release: jammy
Kernel: 5.15.0-52-generic

---------------- DisplayLink info ----------------

Driver version: 1.12.0
DisplayLink service status: 
EVDI service version: 1.12.0

------------------ Graphics card -----------------

Vendor: amdgpu
Subsystem: 
VGA: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne (rev c2)
VGA (3D): 
X11 version: 21.1.3-2ubuntu2.2

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No such file or directory
Contents:
 

-------------------- Monitors --------------------

Providers: number : 5
Provider 0: id: 0x54 cap: 0x9, Source Output, Sink Offload crtcs: 4 outputs: 2 associated providers: 4 name:Unknown AMD Radeon GPU @ pci:0000:04:00.0
Provider 1: id: 0x120 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0xff cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 3: id: 0xde cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 4: id: 0xbd cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting

-------------------------------------------------------------------
```

I am wondering is this an issue with the displaylink I bought, or is it an issue with drivers installation?

Thank you,

Sherif

**Comment by Barabazs** [comment]
This does not seem to be an issue with `displaylink-debian`. You can either try to fine tune the config or contact the support desk for your device.
