### ISSUE TITLE
The computer does not start if the dock is plugged in at boot time

### ISSUE THREAD

**Issue by neonicoo** [AdnanHodzic/displaylink-debian#764]
--------------- Linux system info ----------------

Distro: Linuxmint
Release: vanessa
Kernel: 5.15.0-53-generic

---------------- DisplayLink info ----------------

Driver version: 1.12.0
DisplayLink service status: up and running
EVDI service version: 1.12.0

------------------ Graphics card -----------------

Vendor: i915
Subsystem: GT1
VGA: Intel Corporation TigerLake-H GT1 [UHD Graphics] (rev 01)
VGA (3D): NVIDIA Corporation TU117GLM [T1200 Laptop GPU] (rev a1)
X11 version: 21.1.3-2ubuntu2.3
X11 configs: /etc/X11/xorg.conf.d/20-displaylink.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "intel"
EndSection

Section "Device"
    Identifier "intel"
    Driver "modesetting"
    Option "AccelMethod" "None"
EndSection

Section "Screen"
    Identifier "intel"
    Device "intel"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    Option "ConstrainCursor" "off"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration" "on"
    Option "IgnoreDisplayDevices" "CRT"
EndSection

-------------------- Monitors --------------------

Providers: number : 6
Provider 0: id: 0x217 cap: 0x1, Source Output crtcs: 0 outputs: 0 associated providers: 5 name:NVIDIA-0
Provider 1: id: 0x317 cap: 0x6, Sink Output, Source Offload crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0x2f6 cap: 0x6, Sink Output, Source Offload crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 3: id: 0x2d5 cap: 0x6, Sink Output, Source Offload crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 4: id: 0x2b4 cap: 0x6, Sink Output, Source Offload crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 5: id: 0x240 cap: 0x6, Sink Output, Source Offload crtcs: 4 outputs: 6 associated providers: 1 name:modesetting

When I turn on my computer (HP zbook power G8) and the dock is connected in usb-c to it, the computer remains stuck on the linux mint logo and does not start. I am obliged to connect my dock only once the computer has correctly started.

Note that I have the same problem with my second computer (lenovo legion 5), under linux mint 21 with the same kernel 5.15.

**Comment by erzhan89** [comment]
on my Thinkpad X1 Extreme gen 2. I had same issue.. 
Fix was to Disable security of Thunderbolt 3 in BIOS.

**Comment by neonicoo** [comment]
Hi @erzhan89 , thanks for your answer.
I have the same issue with my Lenovo legion 5 15ach6h which is not thunderbold 3 compatible ...

**Comment by neonicoo** [comment]
EDITO: in fact my computer starts, but after a very long time, more or less 10min with the dock connected, against 5-10s without the dock.

**Comment by Barabazs** [comment]
It's a known issue, but unfortunately without a solution for now... 

> EDITO: in fact my computer starts, but after a very long time, more or less 10min with the dock connected, against 5-10s without the dock.

 
> I also noticed that neither redshift nor any other temperature control application works on the external displays connected via displaylink

This is also a known issue. Upstream support is needed, but very unlikely to ever happen...
https://github.com/DisplayLink/evdi/issues/44
