### ISSUE TITLE
Fix Readme.md to Accurately List Supported Kernels

### ISSUE THREAD

**Issue by f1d094** [AdnanHodzic/displaylink-debian#771]
Readme.md states "...regardless of which Linux kernel version (>4.15) you're using." which is not accurate. After upgrading to kernel 6.0, I was disappointed to be greeted with:

`Unsuported kernel version: 6.0
Please wait for a stable DisplayLink release or try to install the beta
No support will be given for the beta version`

Please update Readme.md to set expectations appropriately.

**Comment by Barabazs** [comment]
Kernel check has been removed in #775
