### ISSUE TITLE
Don't detect third monitor

### ISSUE THREAD

**Issue by Domargz** [AdnanHodzic/displaylink-debian#777]
Hi everyone, I'm David and I have a second monitor with a USB c to HDMI and install displaylink to connect the 3rd monitor to my laptop with a USB 3.0 to HDMI, but it doesn't recognize. I have the next output from  ./displaylink-debian.sh --debug, I delete /etc/X11/xorg.conf.d/20-displaylink.conf file.

--------------- Linux system info ----------------

Distro: Debian
Release: bullseye
Kernel: 5.10.0-20-amd64

---------------- DisplayLink info ----------------

Driver version: 1.12.0
1.9.0+dfsg
DisplayLink service status: up and running
EVDI service version: 1.12.0

------------------ Graphics card -----------------

Vendor: i915
Subsystem: 
VGA: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620]
VGA (3D): 
X11 version: 1.20.11-1+deb11u4

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No such file or directory
Contents:
 

-------------------- Monitors --------------------

Providers: number : 5
Provider 0: id: 0x44 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 2 associated providers: 4 name:modesetting
Provider 1: id: 0x148 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0x126 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 3: id: 0x104 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 4: id: 0xe2 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting

Thanks.

**Comment by Barabazs** [comment]
The issue you're describing is not related to `displaylink-debian`.
I would suggest asking on the displaylink forums or on the appropriate stackoverflow.
