### ISSUE TITLE
Primary Display is disabled and cannot enable it again

### ISSUE THREAD

**Issue by yoharsh14** [AdnanHodzic/displaylink-debian#781]
1.Only Secondary display is enabled and the primary display is disabled.
2.cannot enable primary display.
3.Whenever I reboot my system only secondary display works.
### How can I enable my primary display or revert back the display link procedure

**Comment by BainBan** [comment]
I have the same problem what's the fix?!?! I can uninstall and my primary works fine but not my secondary

**Comment by Barabazs** [comment]
Please post the output of `sudo ./displaylink-debian.sh --debug`
