### ISSUE TITLE
kubuntu support / displaylink status empty

### ISSUE THREAD

**Issue by stoky996** [AdnanHodzic/displaylink-debian#790]
Hi i wanted to install this onto my Kubuntu install thinking i would give it a shot as Kubuntu is based off of Ubuntu when installing the displaylink driver i had no issues and the same with this driver although slow loading times on first load of the script where noted. installing the driver was also all fine.

then i got to the post installation section and it said to go into debug and see if the displaylink version shows up and this is what i saw.

![image](https://user-images.githubusercontent.com/54763699/218313613-f04bec77-21e2-40fe-b61a-2315e9e063a1.png)

i thought i did something wrong so i reinstalled both same thing. i also tried installing it in my desktop environment (which is KDE btw) in both Weyland and X11 modes and still the same thing i also attempted to install it when using the Noueavu Driver for NVIDIA GPU's still had the same thing and subsequently reinstalled the open proprietary NVIDIA driver due to random freezing.

i was also wondering if KDE was even supported? as that is the environment i use. and in the settings menu nothing else shows up nothing really changes and the version i install comes direct from display links website.

Regards Jesse and thanks for any help.

**Comment by Barabazs** [comment]
> ![image](https://user-images.githubusercontent.com/54763699/218313613-f04bec77-21e2-40fe-b61a-2315e9e063a1.png)
> 

EVDI service version warns that evdi has not been found. This indicates that the install was not entirely successful.
Please try to run the uninstall procedure first, reboot and then try to install again, but make sure to copy and paste the terminal output here so I can have a look.

> i was also wondering if KDE was even supported? 
> 
I don't know. You'll have to try and report back.
