### ISSUE TITLE
Support for Elementary OS Horus

### ISSUE THREAD

**Issue by standevenjw** [AdnanHodzic/displaylink-debian#804]
------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

--------------- Linux system info ----------------

Distro: Elementary
Release: horus
Kernel: 5.15.0-58-generic

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: i915
Subsystem: [UHD
VGA: Intel Corporation CometLake-S GT2 [UHD Graphics 630] (rev 05)
VGA (3D): 
X11 version: 21.1.3-2ubuntu2.8

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No such file or directory
Contents:
 

-------------------- Monitors --------------------

Providers: number : 1
Provider 0: id: 0x47 cap: 0x9, Source Output, Sink Offload crtcs: 3 outputs: 6 associated providers: 0 name:modesetting

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

**Comment by Barabazs** [comment]
I have added this version to the supported OS.
Please download the latest version from github and try again.
