### ISSUE TITLE
Monitor not detected

### ISSUE THREAD

**Issue by gedelcast** [AdnanHodzic/displaylink-debian#809]
After launching .run script, still no screen.
I tried various xorg.conf found on the forum, but no change.
I had the display only once during the login screen, but stopped after login (don't remember the setting).
It works fine on windows with the same devices
The PC : Lenovo Yoga with Nvidia and Intel Graphics cards ( Ubuntu lunar, kernel 5.19, xorg) - tried with both cards. The only time it worked was (I think) with nvidia card and intel setting.
The link Targus 120 EUZ-50
The output of the debug mode
 sudo ./displaylink-debian.sh --debug
libkmod: ERROR ../libkmod/libkmod-config.c:712 kmod_config_parse: /etc/modprobe.d/alsa-base.conf line 46: ignoring bad line starting with 'options'
libkmod: ERROR ../libkmod/libkmod-config.c:712 kmod_config_parse: /etc/modprobe.d/alsa-base.conf line 46: ignoring bad line starting with 'options'

-------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] 

Are the first lines with libkmod the origin of the problem ?

-------------- Linux system info ----------------

Distro: Ubuntu
Release: kinetic
Kernel: 5.19.0-38-generic

---------------- DisplayLink info ----------------

Driver version: 1.12.0
DisplayLink service status: up and running
EVDI service version: 1.12.0

------------------ Graphics card -----------------

Vendor: i915
Subsystem: [HD
VGA: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
VGA (3D): NVIDIA Corporation GM108M [GeForce 940M] (rev a2)
X11 version: 21.1.4-2ubuntu1.7
X11 configs: /etc/X11/xorg.conf.d/20-displaylink.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "intel"
EndSection

Section "Device"
    Identifier "intel"
    Driver "modesetting"
    Option "AccelMethod" "None"
EndSection

Section "Screen"
    Identifier "intel"
    Device "intel"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    Option "ConstrainCursor" "off"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration" "on"
    Option "IgnoreDisplayDevices" "CRT"
EndSection
Section "OutputClass"
    Identifier  "DisplayLink"
    MatchDriver "evdi"
    Driver      "modesetting"
    Option      "AccelMethod" "none"
EndSection
Section "Device"
  Identifier "DisplayLink"
  Driver "modesetting"
  Option "PageFlip" "false"
EndSection 

-------------------- Monitors --------------------

Providers: number : 6
Provider 0: id: 0x43 cap: 0x0 crtcs: 3 outputs: 2 associated providers: 0 name:modesetting
Provider 1: id: 0x10b cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 2: id: 0xea cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 3: id: 0xc9 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 4: id: 0xa8 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
Provider 5: id: 0x87 cap: 0x0 crtcs: 0 outputs: 0 associated providers: 0 name:modesetting

Probably I am not far from the solution, but some help would be appreciated.

Many thanks

**Comment by Barabazs** [comment]
You have to associate the providers, as noted in the [post-install-guide#display-detection](https://github.com/AdnanHodzic/displaylink-debian/blob/master/post-install-guide.md#display-detection).
