### ISSUE TITLE
Kali 2023.1 i-tec driver issues 

### ISSUE THREAD

**Issue by Runtime48** [AdnanHodzic/displaylink-debian#812]
Hi 

I am trying to obtain and install the display link drivers. Looking at the supported platforms 2022.1 is the latest version supported however I have just installed 2023.1. I have downloaded the repo as per the Github post but had no joy. could you update to the latest Kali version please.  

Please see below from the --debug 

--------------- Linux system info ----------------

Distro: Kali
Release: kali-rolling
Kernel: 6.1.0-kali5-amd64

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: i915
nouveau
Subsystem: Graphics
[Quadro
VGA: Intel Corporation HD Graphics 530 (rev 06)
NVIDIA Corporation GM204GLM [Quadro M3000M] (rev a1)
VGA (3D): 
X11 version: 21.1.7-1

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No such file or directory
Contents:
 

-------------------- Monitors --------------------

Providers: number : 0

**Comment by Barabazs** [comment]
I have added this version to the supported OS.
Please download the latest version from github and try again.
