### ISSUE TITLE
Install is successful after running script. But GUI won't load on reboot.

### ISSUE THREAD

**Issue by losocio** [AdnanHodzic/displaylink-debian#825]
Hi,

I've looked around past summited issues and found one similar to my problem. But it seems to have been abandoned by OP.
The issue: https://github.com/AdnanHodzic/displaylink-debian/issues/784

After a seemingly successful install, I reboot as requested. Reboot isn't successful, as it gets stuck with a blinking cursor (I think it's X crashing but I'm not sure, I'm new to Linux). After that, I don't know what to do. So, taking my inexperience into account, I just play it safe and load the latest system snapshot.

Here is my debug output:
```
Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

--------------- Linux system info ----------------

Distro: Linuxmint
Release: vera
Kernel: 5.15.0-71-generic

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: i915
nvidia
Subsystem: GT2
[GeForce
VGA: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
VGA (3D): 
X11 version: 21.1.4-2ubuntu1.7~22.04.1

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No such file or directory
Contents:
 

-------------------- Monitors --------------------

Providers: number : 2
Provider 0: id: 0x44 cap: 0x9, Source Output, Sink Offload crtcs: 3 outputs: 3 associated providers: 1 name:modesetting
Provider 1: id: 0x1f3 cap: 0x2, Sink Output crtcs: 4 outputs: 3 associated providers: 1 name:NVIDIA-G0
```

I get `DisplayLink service status: EVDI service version: /sys/devices/evdi/version not found`, just like the previously mentioned user.

Thanks in advance!

**Comment by boris-ankov** [comment]
Same issue here.. this is frustrating.. (please view my comments in #826 & #785)

**Comment by iamdey** [comment]
This is probably due to an error when building evdi, see #821 
I think this should be closed as duplicate

**Comment by Barabazs** [comment]
@losocio it appears that there is a problem with installing evdi:
`EVDI service version: /sys/devices/evdi/version not found`

I would suggest retrying the install procedure and copy pasting the entire install terminal output here.

**Comment by mzhk** [comment]
See https://github.com/AdnanHodzic/displaylink-debian/issues/828#issuecomment-1580946097

**Comment by losocio** [comment]
I'll try to fix it later. Busy rn
