### ISSUE TITLE
second time suspend, monitors keep sleeping

### ISSUE THREAD

**Issue by joh4nd** [AdnanHodzic/displaylink-debian#834]
Are you familiar with, or know how to troubleshoot why, monitors wake up after suspend one time, but not a second time? The driver otherwise works fine.

Please be aware, that I installed the driver for Ubuntu on Debian bullseye, not using this repository. Still I hope you may be able to help. The question is also raised on [stackexchange](https://unix.stackexchange.com/questions/746739/why-after-suspend-do-monitors-wake-up-only-sometimes-and-how-to-fix-displayli) and [displaylink forum](https://displaylink.org/forum/showthread.php?p=95399).

**Comment by Barabazs** [comment]
No, that's the first time I'm hearing about this issue.
