### ISSUE TITLE
Debain 12 Bookworm Install Error

### ISSUE THREAD

**Issue by 0xBinarySl3uth** [AdnanHodzic/displaylink-debian#855]
Hi there, 

I encounter the following error when I am trying to install the displaylink driver:

sudo bash displaylink-debian.sh 

<--SNIP-->

Installing driver version: 5.7

Distribution discovered: No LSB modules are available.
Debian GNU/Linux 12 (bookworm)
'evdi' Debian package appears to be installed.
This installer is incompatible with the packaged driver.

-------------------------------------------------------------------

Performing post install steps

ln: failed to create symbolic link '/opt/displaylink/libstdc++.so.6': No such file or directory

**Comment by Heartnett** [comment]
@0xBinarySl3uth 

https://github.com/AdnanHodzic/displaylink-debian/issues/805#issuecomment-1634037909

**Comment by Barabazs** [comment]
Closing this issue in favor of new meta issue where I'll group all related issues.
