### ISSUE TITLE
URL of  Post Installation Guide broken

### ISSUE THREAD

**Issue by acomjean** [AdnanHodzic/displaylink-debian#861]
Its a very minor point:  Thanks for the package. 

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] N

Please read Post Installation Guide: http://bit.ly/2TbZleK

redirects to: https://github.com/AdnanHodzic/displaylink-debian/blob/master/post-install-guide.md

but that page doesn't work.  I found the guide, it should link to here:

https://github.com/AdnanHodzic/displaylink-debian/blob/master/docs/post-install-guide.md

**Comment by acomjean** [comment]
And the second link is also broken.  Love the humor.


Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] B

-----------------------------

Wrong value. Concentrate!

-----------------------------

**Comment by devincurrie** [comment]
Same issue too.

**Comment by Barabazs** [comment]
Thank you for reporting this.
