### ISSUE TITLE
It didn't work for me

### ISSUE THREAD

**Issue by jadsgithub** [AdnanHodzic/displaylink-debian#862]
--------------- Linux system info ----------------

Distro: Ubuntu
Release: jammy
Kernel: 6.2.0-31-generic

---------------- DisplayLink info ----------------

Driver version: 1.12.0+dfsg
1.14.1
DisplayLink service status: up and running
EVDI service version: 1.14.1

------------------ Graphics card -----------------

Vendor: i915
Subsystem: [UHD
VGA: Intel Corporation CometLake-U GT2 [UHD Graphics] (rev 02)
VGA (3D): 
X11 version: 21.1.4-2ubuntu1.7~22.04.1
X11 configs: /etc/X11/xorg.conf.d/20-displaylink.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
 Section "Device"
    Identifier  "Intel"
    Driver      "intel"
EndSection

-------------------- Monitors --------------------

Providers: number : 1
Provider 0: id: 0x45 cap: 0x9, Source Output, Sink Offload crtcs: 4 outputs: 3 associated providers: 0 name:Intel

-------------------------------------------------------------------

**Comment by alexwebgr** [comment]
have you tried installing the official [drivers](https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu)?
it works just fine for me

**Comment by jadsgithub** [comment]
Yes, I installed the official drivers. The Drive is listing when I run `lsusb` but the monitor gives no signal.

`Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 5986:2130 Acer, Inc Integrated Camera
Bus 001 Device 004: ID 0461:0010 Primax Electronics, Ltd HP PR1101U / Primax PMX-KPR1101U Keyboard
-> Bus 001 Device 007: ID 17e9:03c1 DisplayLink USB graphic adapter
Bus 001 Device 006: ID 8087:0aaa Intel Corp. Bluetooth 9460/9560 Jefferson Peak (JfP)
Bus 001 Device 002: ID 30fa:1701 INSTANT USB GAMING MOUSE 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
`
Perhaps the problem is elsewhere. Any idea what it could be?

**Comment by alexwebgr** [comment]
not really :( my problem was that evdi was not found or not installed in the right place, by those drivers so installing the official ones fixed it.
