### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by 99Key-357** [AdnanHodzic/displaylink-debian#865]
hi, I can't connect my hubspot to connect multiple monitors, I followed the procedures but it doesn't work, this is the debug output

--------------- Linux system info ----------------

Distro: Linuxmint
Release: victoria
Kernel: 5.15.0-84-generic

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: i915
Subsystem: [Iris
VGA: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
VGA (3D): NVIDIA Corporation GP108M [GeForce MX330] (rev a1)
X11 version: 21.1.4-2ubuntu1.7~22.04.1

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No such file or directory
Contents:
 

-------------------- Monitors --------------------

Providers: number : 2
Provider 0: id: 0x44 cap: 0x9, Source Output, Sink Offload crtcs: 4 outputs: 2 associated providers: 1 name:modesetting
Provider 1: id: 0xa9 cap: 0x4, Source Offload crtcs: 0 outputs: 0 associated providers: 1 name:modesetting

-------------------------------------------------------------------

**Comment by Barabazs** [comment]
Driver version:
    DisplayLink service status:
    EVDI service version: /sys/devices/evdi/version not found

This indicates that the installation failed. Please try reinstalling and if the issue persists, post the output of the installation procedure.
