### ISSUE TITLE
Please add support for Mint LDME 6 faye

### ISSUE THREAD

**Issue by DG0lden** [AdnanHodzic/displaylink-debian#869]
LDME6 is released based on Debian 12 Bookworm.

There is a need to support this release by this great tool.

Please note that as of now envi-dkms has version 1.12.0 in bookworm repositories. This version doesn't support kernels 6.x that are used by LDME 6 by default.

**Comment by bc1000** [comment]
as quick fix, I just appended "faye" in displaylink-debian.sh:

 in line 205 after "vera": `|| [ $codename == "faye" ]`
