### ISSUE TITLE
Linux parrot 6.5.0-13 not supported

### ISSUE THREAD

**Issue by MegaTobyOne** [AdnanHodzic/displaylink-debian#893]
-------------------------------------------------------------------

Starting Debug ...

Did you read Post Installation Guide? http://bit.ly/2TbZleK [y/N] y

Did you read Troubleshooting most common issues? http://bit.ly/2Rofd0x [y/N] y

--------------- Linux system info ----------------

Distro: Debian
Release: lory
Kernel: 6.5.0-13parrot1-amd64

---------------- DisplayLink info ----------------

Driver version: 
DisplayLink service status: 
EVDI service version: /sys/devices/evdi/version not found

------------------ Graphics card -----------------

Vendor: i915
Subsystem: Haswell-ULT
VGA: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)
VGA (3D): 
X11 version: 21.1.7-3+deb12u5
X11 configs: /etc/X11/xorg.conf.d/00-keyboard.conf

-------------- DisplayLink xorg.conf -------------

File: /etc/X11/xorg.conf.d/20-displaylink.conf
cat: /etc/X11/xorg.conf.d/20-displaylink.conf: No such file or directory
Contents:
 

-------------------- Monitors --------------------

Providers: number : 1
Provider 0: id: 0x46 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 5 associated providers: 0 name:modesetting

-------------------------------------------------------------------

Use this information when submitting an issue (http://bit.ly/2GLDlpY)

-------------------------------------------------------------------

**Comment by 4SH-gaupee** [comment]
Hi, I do not use parrot but could you try to modify the script and add the release name under the Parrot check here https://github.com/AdnanHodzic/displaylink-debian/blob/898d3d120e2cdb6d12ef1f83d8eb2611b9055562/displaylink-debian.sh#L255 ? Tell me if it's working
