### ISSUE TITLE
Acceleration for Displaylink Dock.

### ISSUE THREAD

**Issue by gnutechie** [AdnanHodzic/displaylink-debian#894]
Hey guys,

I've just managed to set a Displaylink dock as a second seat on a mini PC running Debian 12 Cinnamon (Xorg). But the framerate in 1920x1080p@60 kinda sucks... is there a way to accelerate DisplayLink devices so we can enjoy 60 fps (or even 30 will do at the very least as long as it doesn't stutter and loses frames).

**Comment by Barabazs** [comment]
You'll have to reach out to the DisplayLink folks. This project only serves as a tool to install DL and can't help you with that.
