### ISSUE TITLE
Green Screen kali rolling 2017.2

### ISSUE THREAD

**Issue by sycohexor** [AdnanHodzic/displaylink-debian#91]
so at first it would show some text before i installed your script, but then would go blank after the screen would say retrieving data then end up with no signal. After installing the script first it was completely blank, upon boot it would say retrieving data then no signal. Then after another reboot it started showing he green screen. I then attempted the steps in your last post but still xrandr and arandr dont show the monitor and the screen is still green. I tried changing the script codename from 2016.2 to 2017.2 but same thing. What else can i try, i do have another monitor attached which is hdmi but not usb of course, and an hp laptop dv7 6c23cl.

uname -a = 4.12.0-kali2-amd64 #1 SMP Debian 4.12.13-1kali2 (2017-10-03) x86_64 GNU/Linux

lsusb = Bus 003 Device 002: ID 17e9:4015 DisplayLink 

xrandr --listproviders = Providers: number : 1

Provider 0: id: 0x54 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 2 outputs: 3 associated providers: 0 name:SUMO @ pci:0000:00:01.0

sudo systemctl status dlm.service = ● dlm.service - DisplayLink Manager Service
   Loaded: loaded (/lib/systemd/system/dlm.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2017-10-07 17:35:57 PDT; 21min ago
  Process: 804 ExecStartPre=/bin/sh -c modprobe evdi || (dkms install evdi/1.3.54 && modpr
 Main PID: 812 (DisplayLinkMana)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/dlm.service
           └─812 /opt/displaylink/DisplayLinkManager

Oct 07 17:35:56 SycoHexor systemd[1]: Starting DisplayLink Manager Service...
Oct 07 17:35:57 SycoHexor systemd[1]: Started DisplayLink Manager Service.

**Comment by Sorsnce** [comment]
If you are getting a green screen in kali run the following command and reply with the results.

cat /etc/modules-load.d/udl.conf

**Comment by AdnanHodzic** [comment]
Closing the issue due to inactivity.
