### ISSUE TITLE
Problem installing in Debian 12

### ISSUE THREAD

**Issue by Gabrielmr-QC** [AdnanHodzic/displaylink-debian#927]
Hi,

I been trying to install displaylink-debian on Debian 12. However I am getting the following error:

Preparing for install

Archive:  DisplayLink_Ubuntu_6.0.zip
  inflating: 6.0/displaylink-driver-6.0.0-24.run  
  inflating: 6.0/DisplayLink USB Graphics Software for Ubuntu 6.0-Release Notes.txt  
Creating directory displaylink-driver-6.0.0
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing DisplayLink Linux Driver 6.0.0  100%  
patching file 6.0/displaylink-driver-6.0/displaylink-installer.sh
patch unexpectedly ends in middle of line
Hunk #1 FAILED at 237.
1 out of 1 hunk FAILED -- saving rejects to file 6.0/displaylink-driver-6.0/displaylink-installer.sh.rej

Inside the 6.0/displaylink-driver-6.0/displaylink-installer.sh.rej file I have the following:

```
--- displaylink-installer.sh
+++ displaylink-installer.sh
@@ -237,15 +237,15 @@
   printf '\n%s\n%s\n' "Please read the FAQ" \
         "http://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu"
 
-  printf "\n\n%s\n%s\n%s\n\n\n" "Reboot required" "DisplayLink driver installed successfully." \
-        "Please reboot your computer to ensure the proper functioning of the software." \
-      && prompt_yes_no "Do you want to reboot now?" \
-        && reboot
+  # printf "\n\n%s\n%s\n%s\n\n\n" "Reboot required" "DisplayLink driver installed successfully." \
+  #       "Please reboot your computer to ensure the proper functioning of the software." \
+  #     && prompt_yes_no "Do you want to reboot now?" \
+  #       && reboot
 
-  "$NOREBOOT" && exit 0
+  # "$NOREBOOT" && exit 0
 
-  xorg_running || exit 0
-  prompt_yes_no "Xorg is running. Do you want to reboot now?" && reboot
+  # xorg_running || exit 0
+  # prompt_yes_no "Xorg is running. Do you want to reboot now?" && reboot
   exit 0
 }
```
Do you have any idea on how to fix the error

Kind regards

**Comment by Barabazs** [comment]
New version was released yesterday. I'll try to fix it later today.

**Comment by Barabazs** [comment]
I just pushed a new update that should solve this issue.
Please reopen the issue if it persists.
